---
title: "Course support"
---

Most of you will need help at some point and we want to make sure you can identify when that is without getting too frustrated and feel comfortable seeking help.

## Lectures and labs

If you have a question during lecture or lab, feel free to ask it! There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.

## Office hours

The teaching team is here to help you be successful in the course. You are encouraged to attend office hours during the times posted on the home page to ask questions about the course content and assignments. A lot of questions are most effectively answered in-person, so office hours are a valuable resource. I encourage each and every one of you to take advantage of this resource! Make a pledge to stop by office hours at least once during the first three weeks of class. If you truly have no questions to ask, just stop by and say hi and introduce yourself. You can find a list of everyone's office hours [here](/course-team.html).

## Discussion forum

Have a question that can't wait for office hours? Prefer to write out your question in detail rather than asking in person? The online discussion forum is the best venue for these! We will use [Brightspace Discussions](https://brightspace.uwindsor.ca/d2l/le/144921/discussions/topics/61435/View) as the online discussion forum. There is a chance another student has already asked a similar question, so please check the other posts before adding a new question. If you know the answer to a question that is posted, I encourage you to respond!

## Email

Please refrain from emailing any course content questions (those should go [Brightspace Discussions](https://brightspace.uwindsor.ca/d2l/le/144921/discussions/topics/61435/View)), and only use email for questions about personal matters that may not be appropriate for the public course forum (e.g., illness, accommodations, etc.). For such matters, you may email Dr. Lou Odette at [lodette\@uwindsor.ca](#0).

If there is a question that's not appropriate for the public forum, you are welcome to email me directly. **If you email me, please include "BSMM-8740" in the subject line.** Barring extenuating circumstances, I will respond to BSMM-8740 emails within 48 hours Monday - Friday. Response time may be slower for emails sent Friday evening - Sunday.

## Mental health and wellness

Student mental health and wellness is of primary importance at UWindsor, and the university offers resources to support students in managing daily stress and self-care. Uwindsor offers resources for students to seek assistance on coursework and to nurture daily habits that support overall well-being, some of which are listed below:

-   **MySSP**: 1-844-451-9700, [MySSP](https://myssp.app/keepmesafe/ca/home)

-   [off-campus resources](https://www.uwindsor.ca/wellness/)

If your mental health concerns and/or stressful events negatively affect your daily emotional state, academic performance, or ability to participate in your daily activities, many resources are available to help you through difficult times. Duke encourages all students to access these resources.

## **Course materials costs**

There are no costs associated with this course. All readings will come from freely available, open resources (open-source textbooks, journal articles, etc.).
