---
title: "BSMM-8740: Data Analytic Methods & Algorithms"
tbl-colwidths: [5,10,30,5,5,5,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the Fall 2024 semester. Note that this schedule will be updated as the semester progresses, with all changes documented here.

::: column-screen-inset-right
|                Week                | Date        | Topic                                  |                                  Prepare                                  |                                        Slides                                        |                                                   AE                                                    |                                          Lab                                           |                                            Lab Solution                                            | Exam                                                                                          | Project |
|:----------------------------------:|-------------|----------------------------------------|:-------------------------------------------------------------------------:|:------------------------------------------------------------------------------------:|:-------------------------------------------------------------------------------------------------------:|:--------------------------------------------------------------------------------------:|:-----------------------------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------:|:-------:|
| [1](/weeks/BSMM_8740_week_1.html)  | Wed, Sep 11 | Tidyverse, EDA & Git                   | [📖](/weeks/BSMM_8740_week_1.html#prepare){aria-label="Week 1 summary"}   | [🖥️](/slides/BSMM_8740_lec_01.html "Lecture slides"){aria-label="Lecture 1 slides"}  |   [📋](/ae/ae-0-movies.html "Application exercise"){aria-label="Application Exercise 0 instructions"}   |                                                                                        |                                                                                                      |                                                                                              |         |
|                                    |             | Lab 1                                  |                                                                           |                                                                                      |                                                                                                         |  [💻](/labs/BSMM_8740_lab_1.html "Lab instructions"){aria-label="Lab 1 instructions"}  | [⛔](/labs/solutions/2024_8740_lab_1_solutions.html "Lab 1 solutions"){aria-label="Lab 1 solutions"} |                                                                                              |         |
| [2](/weeks/BSMM_8740_week_2.html)  | Wed, Sep 18 | The Recipes Package                    | [📖](/weeks/BSMM_8740_week_2.html#prepare){aria-label="Week 2 summary"}   | [🖥️](/slides/BSMM_8740_lec_02.html "Lecture slides"){aria-label="Lecture 2 slides"}  |                                                                                                         |                                                                                        |                                                                                                      |                                                                                              |         |
|                                    |             | Lab 2                                  |                                                                           |                                                                                      |                                                                                                         |  [💻](/labs/BSMM_8740_lab_2.html "Lab instructions"){aria-label="Lab 2 instructions"}  | [⛔](/labs/solutions/2024_8740_lab_2_solutions.html "Lab 2 solutions"){aria-label="Lab 2 solutions"} |                                                                                              |         |
| [3](/weeks/BSMM_8740_week_3.html)  | Wed, Sep 25 | Regression Methods                     | [📖](/weeks/BSMM_8740_week_3.html#prepare){aria-label="Week 3 summary"}   | [🖥️](/slides/BSMM_8740_lec_03.html "Lecture slides"){aria-label="Lecture 3 slides"}  | [ ](/ae/ae-1-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 1 instructions"} |                                                                                        |                                                                                                      |                                                                                              |         |
|                                    |             | Lab 3                                  |                                                                           |                                                                                      |                                                                                                         |  [💻](/labs/BSMM_8740_lab_3.html "Lab instructions"){aria-label="Lab 3 instructions"}  | [⛔](/labs/solutions/2024_8740_lab_3_solutions.html "Lab 3 solutions"){aria-label="Lab 3 solutions"} |[⛔](/wonk/2024_BSMM_8740_quiz_1_solutions.html "Quiz 1 solutions"){aria-label="Quiz 1 solutions"}|         |
| [4](/weeks/BSMM_8740_week_4.html)  | Wed, Oct 02 | The TidyModels Framework               | [📖](/weeks/BSMM_8740_week_4.html#prepare){aria-label="Week 4 summary"}   | [🖥️](/slides/BSMM_8740_lec_04.html "Lecture slides"){aria-label="Lecture 4 slides"}  |                                                                                                         |                                                                                        |                                                                                                      |                                                                                             |         |
|                                    |             | Lab 4                                  |                                                                           |                                                                                      | [ ](/ae/ae-2-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 2 instructions"} |  [💻](/labs/BSMM_8740_lab_4.html "Lab instructions"){aria-label="Lab 4 instructions"}  | [⛔](/labs/solutions/2024_8740_lab_4_solutions.html "Lab 4 solutions"){aria-label="Lab 4 solutions"} |                                                                                             |         |
| [5](/weeks/BSMM_8740_week_5.html)  | Wed, Oct 09 | Classification & Clustering Methods    | [📖](/weeks/BSMM_8740_week_5.html#prepare){aria-label="Week 5 summary"}   | [🖥️](/slides/BSMM_8740_lec_05.html "Lecture slides"){aria-label="Lecture 5 slides"}  |                                                                                                         |                                                                                        |                                                                                                      |                                                                                             |         |
|                                    |             | Lab 5                                  |                                                                           |                                                                                      | [ ](/ae/ae-2-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 2 instructions"} |  [💻](/labs/BSMM_8740_lab_5.html "Lab instructions"){aria-label="Lab 5 instructions"}  | [⛔](/labs/solutions/2024_8740_lab_5_solutions.html "Lab 5 solutions"){aria-label="Lab 5 solutions"} |[⛔](/wonk/2024_BSMM_8740_midterm_solutions.html "Miderm solutions"){aria-label="Midterm solutions"}|         |
| [6](/weeks/BSMM_8740_week_6.html)  | Wed, Oct 23 | Time Series Methods                    | [📖](/weeks/BSMM_8740_week_6.html#prepare){aria-label="Week 6 summary"}   | [🖥️](/slides/BSMM_8740_lec_06.html "Lecture slides"){aria-label="Lecture 6 slides"}  |                                                                                                         |                                                                                        |                                                                                                      |                                                                                             |         |
|                                    |             | Lab 6                                  |                                                                           |                                                                                      | [ ](/ae/ae-2-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 2 instructions"} |  [💻](/labs/BSMM_8740_lab_6.html "Lab instructions"){aria-label="Lab 6 instructions"}  | [⛔](/labs/solutions/2024_8740_lab_6_solutions.html "Lab 6 solutions"){aria-label="Lab 6 solutions"} |                                                                                             |         |
| [7](/weeks/BSMM_8740_week_7.html)  | Wed, Oct 30 | Causality: DAGs                        | [📖](/weeks/BSMM_8740_week_7.html#prepare){aria-label="Week 7 summary"}   | [🖥️](/slides/BSMM_8740_lec_07.html "Lecture slides"){aria-label="Lecture 7 slides"}  |                                                                                                         |                                                                                        |                                                                                                      |                                                                                             |         |
|                                    |             | Lab 7                                  |                                                                           |                                                                                      | [ ](/ae/ae-2-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 2 instructions"} |  [💻](/labs/BSMM_8740_lab_7.html "Lab instructions"){aria-label="Lab 7 instructions"}  | [⛔](/labs/solutions/2024_8740_lab_7_solutions.html "Lab 7 solutions"){aria-label="Lab 7 solutions"} |[⛔](/wonk/2024_BSMM_8740_quiz_2_solutions.html "Quiz 2 solutions"){aria-label="Quiz 2 solutions"}|         |
| [8](/weeks/BSMM_8740_week_8.html)  | Wed, Oct 06 | Causality: Methods                     | [📖](/weeks/BSMM_8740_week_8.html#prepare){aria-label="Week 8 summary"}   | [🖥️](/slides/BSMM_8740_lec_08.html "Lecture slides"){aria-label="Lecture 8 slides"}  |                                                                                                         |                                                                                        |                                                                                                      |                                                                                             |         |
|                                    |             | Lab 8                                  |                                                                           |                                                                                      | [ ](/ae/ae-2-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 2 instructions"} |  [💻](/labs/BSMM_8740_lab_8.html "Lab instructions"){aria-label="Lab 8 instructions"}  | [⛔](/labs/solutions/2024_8740_lab_8_solutions.html "Lab 8 solutions"){aria-label="Lab 8 solutions"} |                                                                                             |         |
| [9](/weeks/BSMM_8740_week_9.html)  | Wed, Nov 13 | Monte Carlo Methods                    | [📖](/weeks/BSMM_8740_week_9.html#prepare){aria-label="Week 9 summary"}   | [🖥️](/slides/BSMM_8740_lec_09.html "Lecture slides"){aria-label="Lecture 9 slides"}  |                                                                                                         |                                                                                        |                                                                                                      |                                                                                             |         |
|                                    |             | Lab 9                                  |                                                                           |                                                                                      | [ ](/ae/ae-2-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 2 instructions"} |  [💻](/labs/BSMM_8740_lab_9.html "Lab instructions"){aria-label="Lab 9 instructions"}  |                                                                                                      |                                                                                             |         |
| [10](/weeks/BSMM_8740_week_10.html)| Wed, Nov 20 | Bayesian methods \[DRAFT STAGE\]       | [📖](/weeks/BSMM_8740_week_10.html#prepare){aria-label="Week 10 summary"} | [🖥️](/slides/BSMM_8740_lec_10.html "Lecture slides"){aria-label="Lecture 10 slides"} |                                                                                                         |                                                                                        |                                                                                                      |                                                                                             |         |
|                                    |             | Lab 10                                 |                                                                           |                                                                                      | [ ](/ae/ae-2-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 2 instructions"} | [💻](/labs/BSMM_8740_lab_10.html "Lab instructions"){aria-label="Lab 10 instructions"} |                                                                                                      |                                                                                             |         |
| [11](/weeks/BSMM_8740_week_11.html)| Wed, Nov 27 | Advanced Topics  \[DRAFT STAGE\]       | [📖](/weeks/BSMM_8740_week_11.html#prepare){aria-label="Week 11 summary"} | [🖥️](/slides/BSMM_8740_lec_11.html "Lecture slides"){aria-label="Lecture 11 slides"} |                                                                                                         |                                                                                        |                                                                                                      |                                                                                             |         |
|                                    |             | Lab 11                                 |                                                                           |                                                                                      | [ ](/ae/ae-2-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 2 instructions"} | [💻](/labs/BSMM_8740_lab_11.html "Lab instructions"){aria-label="Lab 11 instructions"} |                                                                                                      |                                                                                             |         |
| [12](/weeks/BSMM_8740_week_12.html)| Wed, Dec 04 | Final Exam \[DRAFT STAGE\]             | [📖](/weeks/BSMM_8740_week_12.html#prepare){aria-label="Week 6 summary"}  | [🖥️](/slides/BSMM_8740_lec_12.html "Lecture slides"){aria-label="Lecture 12 slides"} |                                                                                                         |                                                                                        |                                                                                                      |                                                                                             |         |
|                                    |             | Lab 12                                 |                                                                            |                                                                                      | [ ](/ae/ae-2-dcbikeshare.html "Application exercise"){aria-label="Application Exercise 2 instructions"} | [💻](/labs/BSMM_8740_lab_12.html "Lab instructions"){aria-label="Lab 3 instructions"} |                                                                                                      |                                                                                             |         |
:::

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |                                                    Labs                                                    | HW  | Exam | Project | Nada| Huh | Nope|Not done|memo |
|------|------|-------|:-------:|:------:|:---:|:----------------------------------------------------------------------------------------------------------:|:---:|:----:|:-------:|:---:|:---:|:---:|:------:|:---:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786)| ✍️  |  ✅  |   📂    |❎  | ❗  |  ⛔ |   ⏳   | 📝 |
