<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.31">

  <meta name="author" content="L.L. Odette">
  <title>BSMM-8740 - Fall 2025 – Causality</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-156995b38130bdaa56919fb0a5db863b.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Causality – BSMM-8740 - Fall 2025">
<meta property="og:description" content="BSMM8740-2-R-2024F [WEEK - 7]">
<meta property="og:site_name" content="BSMM-8740 - Fall 2025">
<meta name="twitter:title" content="Causality – BSMM-8740 - Fall 2025">
<meta name="twitter:description" content="BSMM8740-2-R-2024F [WEEK - 7]">
<meta name="twitter:image" content="https://bsmm-8740-fall-2025.github.io/osb/slides/images/twitter-card.png">
<meta name="twitter:creator" content="@lodette">
<meta name="twitter:card" content="summary_large_image">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Causality</h1>
  <p class="subtitle">BSMM8740-2-R-2024F [WEEK - 7]</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
L.L. Odette 
</div>
</div>
</div>

</section>
<section id="recap-of-last-week" class="slide level2">
<h2>Recap of last week</h2>
<ul>
<li><p>Last week we introduced the <code>modeltime</code> and <code>timetk</code> R packages.</p></li>
<li><p>We showed how these integrate into the tidymodels workflows for predicting timeseries.</p></li>
</ul>
</section>
<section id="this-week" class="slide level2">
<h2>This week</h2>
<ul>
<li>Introduction to the fundamental problems of causal inference and the biases of some intuitive estimators,</li>
<li>Develop a basic understanding of the tools used to state and then satisfy causality assumptions,</li>
<li>Understanding of how econometric methods recover treatment effects,</li>
<li>Ability to use these methods and estimate their precision using R.</li>
</ul>
</section>
<section>
<section id="statistical-basis-of-causal-inference" class="title-slide slide level1 center">
<h1>Statistical Basis of Causal Inference</h1>

</section>
<section id="the-fundamental-problems-of-inference" class="slide level2">
<h2>The fundamental problems of inference</h2>
<p>When trying to estimate the effect of a treatment / intervention on an outcome, we face two very difficult problems: the <em>Fundamental Problem of Causal Inference</em> (FPCI) and the <em>Fundamental Problem of Statistical Inference</em> (FPSI).</p>
<p>In this lecture we’ll assume all interventions are binary, e.g.&nbsp;we offer a customer a discount or we don’t; we re-brand a branch office or we don’t.</p>
</section>
<section id="rubin-causal-model-rcm1" class="slide level2">
<h2>Rubin Causal Model (RCM<sup>1</sup>)</h2>
<p>RCM is made of three distinct building blocks:</p>
<ul>
<li>a treatment allocation rule, that decides which unit receives the treatment / intervention;</li>
<li>a definition of potential outcomes that measure how each unit reacts to the treatment;</li>
<li>the switching equation that relates potential outcomes to observed outcomes through the allocation rule.</li>
</ul>
<aside><ol class="aside-footnotes"><li id="fn1"><p>The Rubin Causal Model (RCM), also known as the potential outcomes framework, was developed by Donald Rubin in the 1970s and gained prominence in the 1980s.</p></li></ol></aside></section>
<section id="treatment-allocation" class="slide level2">
<h2>Treatment allocation</h2>
<p>Treatment allocation is represented by the variable <span class="math inline">\(D_i\)</span>, where <span class="math inline">\(D_i=1\)</span> if unit <span class="math inline">\(i\)</span> receives the treatment and <span class="math inline">\(D_i=0\)</span> if unit <span class="math inline">\(i\)</span> does not receive the treatment.</p>
<p>The treatment allocation rule is critical:</p>
<ul>
<li>it switches the treatment on or off for each unit, it is going to be at the source of the FPCI.</li>
<li>the specific properties of the treatment allocation rule are going to matter for the feasibility and bias of various effect estimation methods.</li>
</ul>
</section>
<section id="potential-outcomes" class="slide level2">
<h2>Potential outcomes</h2>
<p>Each unit can be treated or untreated, and so there are two potential outcomes:</p>
<ul>
<li><span class="math inline">\(Y_i^1\)</span>: the outcome unit <span class="math inline">\(i\)</span> will have, if treated</li>
<li><span class="math inline">\(Y_i^0\)</span>: the outcome unit <span class="math inline">\(i\)</span> will have, if not treated</li>
</ul>
</section>
<section id="example" class="slide level2">
<h2>Example</h2>
<div class="cell">
<div class="cell-output-display">
<div id="eqqbtiysyl" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#eqqbtiysyl table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#eqqbtiysyl thead, #eqqbtiysyl tbody, #eqqbtiysyl tfoot, #eqqbtiysyl tr, #eqqbtiysyl td, #eqqbtiysyl th {
  border-style: none;
}

#eqqbtiysyl p {
  margin: 0;
  padding: 0;
}

#eqqbtiysyl .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#eqqbtiysyl .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#eqqbtiysyl .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#eqqbtiysyl .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#eqqbtiysyl .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#eqqbtiysyl .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#eqqbtiysyl .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#eqqbtiysyl .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#eqqbtiysyl .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#eqqbtiysyl .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#eqqbtiysyl .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#eqqbtiysyl .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#eqqbtiysyl .gt_spanner_row {
  border-bottom-style: hidden;
}

#eqqbtiysyl .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#eqqbtiysyl .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#eqqbtiysyl .gt_from_md > :first-child {
  margin-top: 0;
}

#eqqbtiysyl .gt_from_md > :last-child {
  margin-bottom: 0;
}

#eqqbtiysyl .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#eqqbtiysyl .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#eqqbtiysyl .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#eqqbtiysyl .gt_row_group_first td {
  border-top-width: 2px;
}

#eqqbtiysyl .gt_row_group_first th {
  border-top-width: 2px;
}

#eqqbtiysyl .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#eqqbtiysyl .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#eqqbtiysyl .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#eqqbtiysyl .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#eqqbtiysyl .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#eqqbtiysyl .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#eqqbtiysyl .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#eqqbtiysyl .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#eqqbtiysyl .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#eqqbtiysyl .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#eqqbtiysyl .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#eqqbtiysyl .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#eqqbtiysyl .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#eqqbtiysyl .gt_left {
  text-align: left;
}

#eqqbtiysyl .gt_center {
  text-align: center;
}

#eqqbtiysyl .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#eqqbtiysyl .gt_font_normal {
  font-weight: normal;
}

#eqqbtiysyl .gt_font_bold {
  font-weight: bold;
}

#eqqbtiysyl .gt_font_italic {
  font-style: italic;
}

#eqqbtiysyl .gt_super {
  font-size: 65%;
}

#eqqbtiysyl .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#eqqbtiysyl .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#eqqbtiysyl .gt_indent_1 {
  text-indent: 5px;
}

#eqqbtiysyl .gt_indent_2 {
  text-indent: 10px;
}

#eqqbtiysyl .gt_indent_3 {
  text-indent: 15px;
}

#eqqbtiysyl .gt_indent_4 {
  text-indent: 20px;
}

#eqqbtiysyl .gt_indent_5 {
  text-indent: 25px;
}

#eqqbtiysyl .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#eqqbtiysyl div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="customer" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">customer</th>
<th id="Y1" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col"><span class="math inline">\(Y^1\)</span></th>
<th id="Y0" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col"><span class="math inline">\(Y^0\)</span></th>
<th id="D" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col"><span class="math inline">\(\text{D}\)</span></th>
<th id="Y" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col"><span class="math inline">\(\text{outcome Y}\)</span></th>
<th id="treatment-effect" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">treatment effect</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_right" headers="customer">1</td>
<td class="gt_row gt_right" headers="Y1">500</td>
<td class="gt_row gt_right" headers="Y0">450</td>
<td class="gt_row gt_right" headers="D">1</td>
<td class="gt_row gt_right" headers="Y">500</td>
<td class="gt_row gt_right" headers="treatment effect">50</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="customer">2</td>
<td class="gt_row gt_right" headers="Y1">600</td>
<td class="gt_row gt_right" headers="Y0">600</td>
<td class="gt_row gt_right" headers="D">1</td>
<td class="gt_row gt_right" headers="Y">600</td>
<td class="gt_row gt_right" headers="treatment effect">0</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="customer">3</td>
<td class="gt_row gt_right" headers="Y1">800</td>
<td class="gt_row gt_right" headers="Y0">600</td>
<td class="gt_row gt_right" headers="D">0</td>
<td class="gt_row gt_right" headers="Y">600</td>
<td class="gt_row gt_right" headers="treatment effect">200</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="customer">4</td>
<td class="gt_row gt_right" headers="Y1">700</td>
<td class="gt_row gt_right" headers="Y0">750</td>
<td class="gt_row gt_right" headers="D">0</td>
<td class="gt_row gt_right" headers="Y">750</td>
<td class="gt_row gt_right" headers="treatment effect">-50</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div style="font-size: large">
<p>In this example <span class="math inline">\(\text{ATE}=\left(50+0+200-50\right)/4=50\)</span> and <span class="math inline">\(\text{ATT}=\left(50+0\right)/2=25\)</span>.</p>
<p>But this example imagines that we know the counterfactuals (i.e.&nbsp;<span class="math inline">\(Y^0\)</span> for <span class="math inline">\(D=1\)</span> and <span class="math inline">\(Y^1\)</span> for <span class="math inline">\(D=0\)</span>), when we <strong>never</strong> do.</p>
<p>The next example comparing the outcomes with and without treatment is more realistic.</p>
</div>
</section>
<section id="example-1" class="slide level2">
<h2>Example</h2>
<div class="cell">
<div class="cell-output-display">
<div id="tlniizligv" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#tlniizligv table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#tlniizligv thead, #tlniizligv tbody, #tlniizligv tfoot, #tlniizligv tr, #tlniizligv td, #tlniizligv th {
  border-style: none;
}

#tlniizligv p {
  margin: 0;
  padding: 0;
}

#tlniizligv .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#tlniizligv .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#tlniizligv .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#tlniizligv .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#tlniizligv .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#tlniizligv .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#tlniizligv .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#tlniizligv .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#tlniizligv .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#tlniizligv .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#tlniizligv .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#tlniizligv .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#tlniizligv .gt_spanner_row {
  border-bottom-style: hidden;
}

#tlniizligv .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#tlniizligv .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#tlniizligv .gt_from_md > :first-child {
  margin-top: 0;
}

#tlniizligv .gt_from_md > :last-child {
  margin-bottom: 0;
}

#tlniizligv .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#tlniizligv .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#tlniizligv .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#tlniizligv .gt_row_group_first td {
  border-top-width: 2px;
}

#tlniizligv .gt_row_group_first th {
  border-top-width: 2px;
}

#tlniizligv .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#tlniizligv .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#tlniizligv .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#tlniizligv .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#tlniizligv .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#tlniizligv .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#tlniizligv .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#tlniizligv .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#tlniizligv .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#tlniizligv .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#tlniizligv .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#tlniizligv .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#tlniizligv .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#tlniizligv .gt_left {
  text-align: left;
}

#tlniizligv .gt_center {
  text-align: center;
}

#tlniizligv .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#tlniizligv .gt_font_normal {
  font-weight: normal;
}

#tlniizligv .gt_font_bold {
  font-weight: bold;
}

#tlniizligv .gt_font_italic {
  font-style: italic;
}

#tlniizligv .gt_super {
  font-size: 65%;
}

#tlniizligv .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#tlniizligv .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#tlniizligv .gt_indent_1 {
  text-indent: 5px;
}

#tlniizligv .gt_indent_2 {
  text-indent: 10px;
}

#tlniizligv .gt_indent_3 {
  text-indent: 15px;
}

#tlniizligv .gt_indent_4 {
  text-indent: 20px;
}

#tlniizligv .gt_indent_5 {
  text-indent: 25px;
}

#tlniizligv .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#tlniizligv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="customer" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">customer</th>
<th id="Y1" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col"><span class="math inline">\(Y^1\)</span></th>
<th id="Y0" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col"><span class="math inline">\(Y^0\)</span></th>
<th id="D" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col"><span class="math inline">\(\text{D}\)</span></th>
<th id="Y" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col"><span class="math inline">\(\text{outcome Y}\)</span></th>
<th id="treatment-effect" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">treatment effect</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_right" headers="customer">1</td>
<td class="gt_row gt_right" headers="Y1">500</td>
<td class="gt_row gt_right" headers="Y0">NA</td>
<td class="gt_row gt_right" headers="D">1</td>
<td class="gt_row gt_right" headers="Y">500</td>
<td class="gt_row gt_center" headers="treatment effect">NA</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="customer">2</td>
<td class="gt_row gt_right" headers="Y1">600</td>
<td class="gt_row gt_right" headers="Y0">NA</td>
<td class="gt_row gt_right" headers="D">1</td>
<td class="gt_row gt_right" headers="Y">600</td>
<td class="gt_row gt_center" headers="treatment effect">NA</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="customer">3</td>
<td class="gt_row gt_right" headers="Y1">NA</td>
<td class="gt_row gt_right" headers="Y0">600</td>
<td class="gt_row gt_right" headers="D">0</td>
<td class="gt_row gt_right" headers="Y">600</td>
<td class="gt_row gt_center" headers="treatment effect">NA</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="customer">4</td>
<td class="gt_row gt_right" headers="Y1">NA</td>
<td class="gt_row gt_right" headers="Y0">750</td>
<td class="gt_row gt_right" headers="D">0</td>
<td class="gt_row gt_right" headers="Y">750</td>
<td class="gt_row gt_center" headers="treatment effect">NA</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div style="font-size: large">
<p>Given these observations, and comparing the mean of the treated outcomes to the mean of the untreated outcomes: <span class="math inline">\(\text{ATE}\ne\Delta_\text{WW}=\left(500+600\right)/2-\left(600+750\right)/2=-125\)</span>.</p>
<p>The <span class="math inline">\(\Delta_\text{WW}\)</span> is a biased estimate of the <span class="math inline">\(\text{ATE}\)</span> because the untreated are bigger spenders than the treated on average.</p>
</div>
</section>
<section id="switching-equation" class="slide level2">
<h2>Switching equation</h2>
<p>Here is the switching equation. It links the observed outcome to the potential outcomes through the allocation rule:</p>
<p><span class="math display">\[
\begin{align*}
Y_{i} &amp; =\begin{cases}
Y_{i}^{1} &amp; \text{if}\,D_{i}=1\\
Y_{i}^{0} &amp; \text{if}\,D_{i}=0
\end{cases}\\
&amp; =Y_{i}^{1}D_{i}+Y_{i}^{0}\left(1-D_{i}\right)
\end{align*}
\]</span></p>
</section>
<section id="switching-equation-1" class="slide level2">
<h2>Switching equation</h2>
<p>What the switching equation means is that, for each unit <span class="math inline">\(i\)</span> we get to observe only one of the two potential outcomes. we can <u>never</u> see both potential outcomes for the same unit at the same time.</p>
<p>For each of the units, one of the two potential outcomes is unobserved - it is <strong>counterfactual</strong>. It can be conceived by an effort of reason: it is the consequence of what would have happened had some action not been taken.</p>
</section>
<section id="treatment-effects" class="slide level2">
<h2>Treatment effects</h2>
<p>Now we can defined the causal effect:</p>
<p>The unit level treatment effect<sup>1</sup> is defined as</p>
<p><span class="math display">\[
\Delta_i^Y=Y_i^1-Y_i^0
\]</span> (which cannot be observed).</p>
<aside><ol class="aside-footnotes"><li id="fn2"><p>Note that the treatment effects can be heterogeneous (they can differ by unit).</p></li></ol></aside></section>
<section id="treatment-effects-1" class="slide level2">
<h2>Treatment effects</h2>
<p>Average treatment effect on the treated (TT<sup>1</sup>) gives us summary stats (in the <em>population</em> [<span class="math inline">\(TT\)</span>] or <em>sample</em> [<span class="math inline">\(TT_s\)</span>]).</p>
<p><span class="math display">\[
\Delta_{TT_{s}}^{Y}=\frac{1}{\sum_{i=1}^{N}D_{i}}\sum_{i=1}^{N}\left(Y_{i}^{1}-Y_{i}^{0}\right)D_{i}
\]</span> with the corresponding expected value in the population</p>
<p><span class="math display">\[
\Delta_{TT}^{Y}=\mathbb{E}\left[\left.Y_{i}^{1}-Y_{i}^{0}\right|D_{i}=1\right]
\]</span></p>
<aside><ol class="aside-footnotes"><li id="fn3"><p>You’ll sometimes see this written as ATT</p></li></ol></aside></section>
<section id="fundamental-problem-of-causal-inference" class="slide level2">
<h2>Fundamental problem of causal inference</h2>
<p>It is <strong>impossible</strong> to observe TT, either in the <em>population</em> or in the <em>sample</em>.</p>
<p><span class="math display">\[
\begin{align*}
\Delta_{TT_{s}}^{Y} &amp; =\frac{1}{\sum_{i=1}^{N}D_{i}}\sum_{i=1}^{N}\left(Y_{i}^{1}-Y_{i}^{0}\right)D_{i}\\
&amp; =\frac{1}{\sum_{i=1}^{N}D_{i}}\sum_{i=1}^{N}Y_{i}^1D_{i}-\frac{1}{\sum_{i=1}^{N}D_{i}}\sum_{i=1}^{N}Y_{i}^{0}D_{i}
\end{align*}
\]</span> but <span class="math inline">\(Y_{i}^{0}D_{i}\)</span> is unobserved when <span class="math inline">\(D_i=1\)</span>.</p>
</section>
<section id="intuitive-casual-estimators" class="slide level2">
<h2>Intuitive casual estimators</h2>
<p>Intuitive comparisons are often made in order to estimate causal effects, e.g.&nbsp;the <strong>with/without</strong> comparison (<strong>WW</strong>).</p>
<p><strong>WW</strong> compares the average outcomes of the treated units with those of the untreated units.</p>
<p>Intuitive comparisons try to proxy for the expected counterfactual outcome in the treated group by using an observed quantity.</p>
</section>
<section id="intuitive-casual-estimators-1" class="slide level2">
<h2>Intuitive casual estimators</h2>
<p>Unfortunately, these proxies are generally poor and provide biased estimates of TT.</p>
<p>The reason that these proxies are poor is that the treatment is not the only factor that differentiates the treated group from the groups used to form the proxy. The intuitive comparisons are biased because factors other than the treatment are correlated to its allocation.</p>
</section>
<section id="withwithout-comparison" class="slide level2">
<h2>With/Without comparison</h2>
<p><span class="math display">\[
\Delta_{WW}^{Y}=\mathbb{E}\left[\left.Y_{i}\right|D_{i}=1\right] - \mathbb{E}\left[\left.Y_{i}\right|D_{i}=0\right]
\]</span></p>
<p>Note that this is not the same as the treatment effect on the treated (TT):</p>
<p><span class="math display">\[
\Delta_{TT}^{Y}=\mathbb{E}\left[\left.Y_{i}^{1}-Y_{i}^{0}\right|D_{i}=1\right]
\]</span></p>
</section>
<section id="withwithout-comparison-1" class="slide level2">
<h2>With/Without comparison</h2>
<p>The difference <span class="math inline">\(\Delta_{WW}^{Y}-\Delta_{TT}^{Y}\)</span> is called the selection bias <span class="math inline">\(\Delta_{SB}^{Y}\)</span>:</p>
<p><span class="math display">\[
\begin{align*}
\Delta_{SB}^{Y} &amp; =\Delta_{WW}^{Y}-\Delta_{TT}^{Y}\\
&amp; =\mathbb{E}\left[\left.Y_{i}\right|D_{i}=1\right]-\mathbb{E}\left[\left.Y_{i}\right|D_{i}=0\right]-\mathbb{E}\left[\left.Y_{i}^{1}-Y_{i}^{0}\right|D_{i}=1\right]\\
&amp; =\mathbb{E}\left[\left.Y_{i}^{0}\right|D_{i}=1\right]-\mathbb{E}\left[\left.Y_{i}^{0}\right|D_{i}=0\right]
\end{align*}
\]</span></p>
<p>So the selection bias is the difference in the <strong>untreated potential-outcomes</strong> between treatment groups</p>
</section>
<section id="withwithout-comparison-2" class="slide level2">
<h2>With/Without comparison</h2>
<p>Under what conditions would we have</p>
<p><span class="math display">\[
\mathbb{E}\left[\left.Y_{i}^{0}\right|D_{i}=1\right]-\mathbb{E}\left[\left.Y_{i}^{0}\right|D_{i}=0\right]\ne0
\]</span></p>
<p>With non-zero selection bias, selection into the treatment biases the effect of the treatment on outcomes.</p>
</section>
<section id="withwithout-comparison-3" class="slide level2">
<h2>With/Without comparison</h2>
<div style="font-size: smaller">
<ul>
<li><p>Confounding factors are the factors that generate differences between treated and untreated individuals even in the absence of the treatment.</p></li>
<li><p>Suppose we wanted to test giving discounts to our smaller-value customers to induce them to buy more. The results of the test could be biased if small-value customer would just buy less anyway.</p></li>
<li><p>The mere fact of being selected for receiving the discount means that these customers have a host of characteristics that would differentiate them from the unselected customers.</p></li>
</ul>
</div>
</section>
<section id="identification-assumption" class="slide level2">
<h2>Identification assumption</h2>
<p>There is no selection bias if</p>
<p><span class="math display">\[
\mathbb{E}\left[\left.Y_{i}^{0}\right|D_{i}=1\right]-\mathbb{E}\left[\left.Y_{i}^{0}\right|D_{i}=0\right]=0
\]</span></p>
<p>i.e.&nbsp;the expected <em>counterfactual</em> outcome of the <u><strong>treated</strong></u> is equal to the expected potential outcome of the <u><strong>untreated</strong></u> .</p>
<p>This is called the <strong>identification assumption</strong>.</p>
</section>
<section id="identification-assumption-1" class="slide level2">
<h2>Identification assumption</h2>
<p>For the identification assumption to hold, it has to be that <strong>all</strong> the determinants of <span class="math inline">\(D_i\)</span> are actually unrelated to <span class="math inline">\(Y_i^0\)</span>.</p>
<p>One way to <u><strong>enforce</strong></u> this assumption is to randomize treatment assignment.</p>
<p>One way to <u><strong>test</strong></u> for the validity of the identification assumption is to compare the values of observed covariates in the treated and untreated group, because differences in covariates can lead to confounding.</p>
</section>
<section id="identification-assumption-2" class="slide level2">
<h2>Identification assumption</h2>
<p>If the identification assumption holds, and the treatment assignment is (effectively) independent of the outcome, then</p>
<p><span class="math display">\[
\begin{align*}
\Delta_{WW}^{Y} &amp; =\mathbb{E}\left[\left.Y_{i}\right|D_{i}=1\right]-\mathbb{E}\left[\left.Y_{i}\right|D_{i}=0\right]\\
&amp; =\mathbb{E}\left[Y_{i}\right]-\mathbb{E}\left[Y_{i}\right]\\
&amp; =\Delta_{ATE}^{Y}
\end{align*}
\]</span> where <span class="math inline">\(\Delta_{ATE}^{Y}\)</span> is the average treatment effect in the population.</p>
</section>
<section id="fundamental-problems" class="slide level2">
<h2>Fundamental problems</h2>
<ul>
<li>The FPCI states that our causal parameter of interest (<span class="math inline">\(\Delta_{TT}^{Y}\)</span> - the effect of treatment on the treated) is fundamentally unobservable, even when the sample size is infinite.</li>
<li>The FPSI states that, even if we have an estimator <span class="math inline">\(E\)</span> that identifies <span class="math inline">\(\Delta_{TT}^{Y}\)</span> in the population, we cannot observe <span class="math inline">\(E\)</span> because we only have access to a finite sample of the population.</li>
</ul>
</section></section>
<section>
<section id="causal-inference-in-r" class="title-slide slide level1 center">
<h1>Causal Inference in R</h1>

</section>
<section id="causal-inference-workflow" class="slide level2">
<h2>Causal Inference Workflow</h2>
<ol type="1">
<li>Specify a causal question</li>
<li>Draw our assumptions using a causal diagram (DAG)</li>
<li>Model our assumptions</li>
<li>Diagnose our models</li>
<li>Estimate the causal effect</li>
<li>Conduct sensitivity analysis on the effect estimate</li>
</ol>
<div style="font-size: large">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The following material is from <a href="https://www.r-causal.org/">Causal Inference in R</a> by Barrett, D’Agostino McGowan &amp; Gerke under a MIT + file license.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="dags" class="title-slide slide level1 center">
<h1>DAGS</h1>

</section>
<section id="directed-acyclic-graphs-dags" class="slide level2">
<h2>Directed acyclic graphs (DAGs)</h2>

<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-dag-basic-1.png" width="288" class="r-stretch quarto-figure-center" id="fig-dag-basic"><p class="caption">
Figure&nbsp;1: A causal directed acyclic graph (DAG). DAGs depict causal relationships. In this DAG, the assumption is that <code>x</code> causes <code>y</code>.
</p></section>
<section id="dags-1" class="slide level2">
<h2>DAGs</h2>

<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-dag-path-types-1.png" width="960" class="r-stretch quarto-figure-center" id="fig-dag-path-types"><p class="caption">
Figure&nbsp;2: Three types of causal relationships: forks, chains, and colliders. The direction of the arrows and the relationships of interest dictate which type of path a series of variables represents. Forks represent a mutual cause, chains represent direct causes, and colliders represent a mutual descendant.
</p></section>
<section id="dags-2" class="slide level2">
<h2>DAGs</h2>
<div style="font-size: 80%">
<p>Forks represent a common cause of two variables. Here, we’re saying that <code>q</code> causes both <code>x</code> and <code>y</code>, the traditional definition of a confounder. They’re called forks because the arrows from <code>x</code> to <code>y</code> are in different directions.</p>
<p>Chains, on the other hand, represent a series of arrows going in the same direction. Here, <code>q</code> is called a <em>mediator</em>: it is along the causal path from <code>x</code> to <code>y</code>. In this diagram, the only path from <code>x</code> to <code>y</code> is mediated through <code>q</code>.</p>
<p>Finally, a collider is a path where two arrowheads meet at a variable. Because causality always goes forward in time, this naturally means that the collider variable is caused by two other variables. Here, we’re saying that <code>x</code> and <code>y</code> both cause <code>q</code>.</p>
</div>
</section>
<section id="dags-3" class="slide level2">
<h2>DAGs</h2>
<div style="font-size: 80%">
<p>These three types of paths have different implications for the statistical relationship between <code>x</code> and <code>y</code>. If we only look at the correlation between the two variables under these assumptions:</p>
<ol type="1">
<li>In the fork, <code>x</code> and <code>y</code> will be associated, despite there being no arrow from <code>x</code> to <code>y</code>.</li>
<li>In the chain, <code>x</code> and <code>y</code> are related only through <code>q</code>.</li>
<li>In the collider, <code>x</code> and <code>y</code> will <em>not</em> be related.</li>
</ol>
<p>Paths that transmit association are called <strong><em>open paths</em></strong>. Paths that do not transmit association are called <strong><em>closed paths</em></strong>. Forks and chains are open, while colliders are closed.</p>
</div>
</section>
<section id="dags---forks" class="slide level2">
<h2>DAGs - forks</h2>
<div style="font-size: 80%">
<p>So, should we adjust for <code>q</code>, i.e.&nbsp;include <code>q</code> in our model? That depends on the nature of the path.</p>
<p>Forks are confounding paths. Because <code>q</code> causes both <code>x</code> and <code>y</code>, <code>x</code> and <code>y</code> will have a spurious association. They both contain information from <code>q</code>, their mutual cause. That mutual causal relationship makes <code>x</code> and <code>y</code> associated statistically.</p>
<p>Adjusting for <code>q</code>, i.e.&nbsp;fixing the value of <code>q</code>, will <em>block</em> the bias from confounding and give us the true relationship between <code>x</code> and <code>y</code>.</p>
</div>
</section>
<section id="dags---mediators" class="slide level2">
<h2>DAGs - mediators</h2>
<div style="font-size: 80%">
<p>For chains, whether or not we adjust for mediators depends on the research question.</p>
<p>Here, adjusting for <code>q</code> would result in a null estimate of the effect of <code>x</code> on <code>y</code>. Because the only effect of <code>x</code> on <code>y</code> is via <code>q</code>, no other effect remains.</p>
<p>The effect of <code>x</code> on <code>y</code> mediated by <code>q</code> is called the <strong><em>indirect</em></strong> effect, while the effect of <code>x</code> on <code>y</code> directly is called the <strong><em>direct</em></strong> effect. If we’re only interested in the direct effect, controlling for <code>q</code> might be what we want. If we want to know about both effects, we shouldn’t try to adjust for <code>q</code>.</p>
</div>
</section>
<section id="dags---colliders" class="slide level2">
<h2>DAGs - colliders</h2>
<div style="font-size: 80%">
<p>Colliders are different. In the collider DAG of <a href="#/fig-dag-path-types" class="quarto-xref">Figure&nbsp;2</a>, <code>x</code> and <code>y</code> are <em>not</em> associated, but both cause <code>q</code>.</p>
<p>Adjusting for <code>q</code> has the opposite effect than with confounding: it <em>opens</em> a biasing pathway.</p>
<p>Sometimes, people draw the path opened up by conditioning on a collider connecting <code>x</code> and <code>y</code>.</p>
</div>
</section>
<section id="dags---colliders-1" class="slide level2">
<h2>DAGs - colliders</h2>
<div style="font-size: 80%">
<p>How can this be? Since <code>x</code> and <code>y</code> happen before <code>q</code>, <code>q</code> can’t impact them.</p>
<p>Let’s turn the DAG on its side and consider <a href="#/fig-collider-time" class="quarto-xref">Figure&nbsp;3</a> on the next slide. If we break down the two time points, at time point 1, <code>q</code> hasn’t happened yet, and <code>x</code> and <code>y</code> are unrelated. At time point 2, <code>q</code> happens due to <code>x</code> and <code>y</code>. <em>But causality only goes forward in time</em>.</p>
<p><code>q</code> happening later can’t change the fact that <code>x</code> and <code>y</code> happened independently in the past.</p>
</div>
</section>
<section id="dags---colliders-2" class="slide level2">
<h2>DAGs - colliders</h2>

<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-collider-time-1.png" width="960" class="r-stretch quarto-figure-center" id="fig-collider-time"><p class="caption">
Figure&nbsp;3: A collider relationship over two points in time. At time point one, there is no relationship between <code>x</code> and <code>y</code>. Both cause <code>q</code> by time point two, but this does not change what already happened at time point one.
</p></section>
<section id="dags---colliders-3" class="slide level2">
<h2>DAGs - colliders</h2>
<div style="font-size: 80%">
<p>Causality only goes forward. Association, however, is time-agnostic. It’s just an observation about the numerical relationships between variables. When we control for the future, we risk introducing bias. It takes time to develop an intuition for this.</p>
<p>Consider a case where x and y are the only causes of q, and all three variables are binary. When either x or y equals 1, then q happens. If we know q = 1 and x = 0 then logically it must be that y = 1. Thus, knowing about q gives us information about y via x.</p>
<p>This example is extreme, but it shows how this type of bias, sometimes called collider-stratification bias or selection bias, occurs: conditioning on q provides statistical information about x and y and distorts their relationship.</p>
</div>
</section>
<section id="dags-4" class="slide level2">
<h2>DAGs</h2>
<div style="font-size: 80%">
<p>Correctly identifying the causal structure between the exposure and outcome helps us</p>
<ol type="1">
<li>communicate the assumptions we’re making about the relationships between variables, and</li>
<li>identify sources of bias.</li>
</ol>
<p>Importantly, in doing 2), we are also often able to identify ways to prevent bias based on the assumptions in 1). In the simple case of the three DAGs (<a href="#/fig-dag-path-types" class="quarto-xref">Figure&nbsp;2</a>), we know whether or not to control for <code>q</code> depending on the nature of the causal structure. The set or sets of variables we need to adjust for is called the <u><strong>adjustment set</strong></u>. DAGs can help us identify adjustment sets even in complex settings.</p>
</div>
</section>
<section id="dags---exchangeability" class="slide level2">
<h2>DAGs - exchangeability</h2>
<div style="font-size: 80%">
<p>We commonly refer to <u><strong>exchangeability</strong></u> as the assumption of no confounding. Actually, this isn’t quite right. It’s the assumption of no open, non-causal paths. Many times, these are confounding pathways. However, conditioning on a collider can also open paths. Even though these aren’t confounders, doing so creates non-exchangeability between the two groups: they are different in a way that matters to the exposure and outcome.</p>
<p>Open, non-causal paths are also called <u><strong>backdoor paths</strong></u>. We’ll use this terminology often because it captures the idea well: these are any open paths biasing the effect we’re interested in estimating.</p>
</div>
</section>
<section id="dags---exchangeability-vs-identification" class="slide level2">
<h2>DAGs - exchangeability vs identification</h2>
<div style="font-size: 80%">
<ul>
<li>Exchangeability is one of the assumptions that can help in achieving identification. If you can assume exchangeability, then you can often identify the causal effect using the observed data.</li>
<li>Exchangeability is more about the structure of the data and the treatment assignment mechanism, while identification is a broader concept that encompasses the entire process of linking causal models to statistical models and data.</li>
</ul>
</div>
</section>
<section id="dags---visualization" class="slide level2">
<h2>DAGs - visualization</h2>
<div style="font-size: 80%">
<p>To create a DAG object, we’ll use <code>ggdag::dagify()</code> which returns a dagitty object that works with both the <code>dagitty</code> and <code>ggdag</code> packages.</p>
<p>The <code>dagify()</code> function takes formulas, separated by commas, that specify causes and effects, with the left element of the formula defining the effect and the right all of the factors that cause it. This is just like the type of formula we specify for most regression models in R.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a>ggdag<span class="sc">::</span><span class="fu">dagify</span>( </span>
<span id="cb1-2"><a></a>  effect1 <span class="sc">~</span> cause1 <span class="sc">+</span> cause2 <span class="sc">+</span> cause3</span>
<span id="cb1-3"><a></a>  , effect2 <span class="sc">~</span> cause1 <span class="sc">+</span> cause4</span>
<span id="cb1-4"><a></a>  , ...</span>
<span id="cb1-5"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="dags---visualization-1" class="slide level2">
<h2>DAGs - visualization</h2>
<div style="font-size: 80%">
<p>What are all of the factors that cause graduate students to listen to a podcast the morning before an exam? What are all of the factors that could cause a graduate student to do well on a test? Let’s posit some here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a>ggdag<span class="sc">::</span><span class="fu">dagify</span>(</span>
<span id="cb2-2"><a></a>  podcast <span class="sc">~</span> mood <span class="sc">+</span> humor <span class="sc">+</span> prepared,</span>
<span id="cb2-3"><a></a>  exam <span class="sc">~</span> mood <span class="sc">+</span> prepared</span>
<span id="cb2-4"><a></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>dag {
exam
humor
mood
podcast
prepared
humor -&gt; podcast
mood -&gt; exam
mood -&gt; podcast
prepared -&gt; exam
prepared -&gt; podcast
}</code></pre>
</div>
</div>
</div>
</section>
<section id="dags---visualization-2" class="slide level2">
<h2>DAGs - visualization</h2>
<div style="font-size: 80%">
<p>In the code, we assume that:</p>
<ul>
<li>a graduate student’s mood, sense of humor, and how prepared they feel for the exam could influence whether they listened to a podcast the morning of the test, and</li>
<li>their mood and how prepared they are also influence their exam score.</li>
</ul>
<p>Notice we <em>do not</em> see podcast in the exam equation; this means that we assume that there is <strong>no</strong> causal relationship between podcast and the exam score.</p>
</div>
</section>
<section id="dags---visualization-3" class="slide level2">
<h2>DAGs - visualization</h2>
<div style="font-size: 80%">
<p>Some other useful arguments for <code>dagify()</code>:</p>
<ul>
<li><code>exposure</code> and <code>outcome</code>: Telling ggdag the variables that are the exposure and outcome of your research question is required for many of the most valuable queries we can make of DAGs.</li>
<li><code>latent</code>: This argument lets us tell ggdag that some variables in the DAG are unmeasured. <code>latent</code> helps identify valid adjustment sets with the data we actually have.</li>
<li><code>coords</code>: Coordinates for the variables. You can choose between algorithmic or manual layouts, as discussed below. We’ll use <code>time_ordered_coords()</code> here.</li>
<li><code>labels</code>: A character vector of labels for the variables.</li>
</ul>
</div>
</section>
<section id="dags---visualization-4" class="slide level2">
<h2>DAGs - visualization</h2>
<div style="font-size: 80%">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a>podcast_dag <span class="ot">&lt;-</span> ggdag<span class="sc">::</span><span class="fu">dagify</span>(</span>
<span id="cb4-2"><a></a>  podcast <span class="sc">~</span> mood <span class="sc">+</span> humor <span class="sc">+</span> prepared,</span>
<span id="cb4-3"><a></a>  exam <span class="sc">~</span> mood <span class="sc">+</span> prepared,</span>
<span id="cb4-4"><a></a>  <span class="at">coords =</span> ggdag<span class="sc">::</span><span class="fu">time_ordered_coords</span>(</span>
<span id="cb4-5"><a></a>    <span class="fu">list</span>(</span>
<span id="cb4-6"><a></a>      <span class="fu">c</span>(<span class="st">"prepared"</span>, <span class="st">"humor"</span>, <span class="st">"mood"</span>), <span class="co"># time point 1</span></span>
<span id="cb4-7"><a></a>      <span class="st">"podcast"</span>,                      <span class="co"># time point 2</span></span>
<span id="cb4-8"><a></a>      <span class="st">"exam"</span>                          <span class="co"># time point 3</span></span>
<span id="cb4-9"><a></a>    )</span>
<span id="cb4-10"><a></a>  ),</span>
<span id="cb4-11"><a></a>  <span class="at">exposure =</span> <span class="st">"podcast"</span>,</span>
<span id="cb4-12"><a></a>  <span class="at">outcome =</span> <span class="st">"exam"</span>,</span>
<span id="cb4-13"><a></a>  <span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb4-14"><a></a>    <span class="at">podcast =</span> <span class="st">"podcast"</span>,</span>
<span id="cb4-15"><a></a>    <span class="at">exam =</span> <span class="st">"exam score"</span>,</span>
<span id="cb4-16"><a></a>    <span class="at">mood =</span> <span class="st">"mood"</span>,</span>
<span id="cb4-17"><a></a>    <span class="at">humor =</span> <span class="st">"humor"</span>,</span>
<span id="cb4-18"><a></a>    <span class="at">prepared =</span> <span class="st">"prepared"</span></span>
<span id="cb4-19"><a></a>  )</span>
<span id="cb4-20"><a></a>)</span>
<span id="cb4-21"><a></a>ggdag<span class="sc">::</span><span class="fu">ggdag</span>(podcast_dag, <span class="at">use_labels =</span> <span class="st">"label"</span>, <span class="at">text =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb4-22"><a></a>  ggdag<span class="sc">::</span><span class="fu">theme_dag</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-dag-podcast" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-dag-podcast-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-dag-podcast-1.png" width="384">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dag-podcast-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Proposed DAG to answer the question: Does listening to a comedy podcast the morning before an exam improve graduate students’ test scores?
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="dags---open-paths" class="slide level2">
<h2>DAGs - open paths</h2>
<div style="font-size: 80%">
<p>We’ve specified the DAG for this question and told <code>ggdag</code> what the exposure and outcome of interest are. According to the DAG, there is no direct causal relationship between listening to a podcast and exam scores.</p>
<p>Are there any other open paths? <code>ggdag_paths()</code> takes a DAG and visualizes the open paths.</p>
<p>In <a href="#/fig-paths-podcast" class="quarto-xref">Figure&nbsp;5</a> (next slide), we see two open paths:</p>
<ul>
<li><code>podcast &lt;- mood -&gt; exam</code> and</li>
<li><code>podcast &lt;- prepared -&gt; exam</code>.</li>
</ul>
<p>These are both forks—<em>confounding pathways</em>. Since there is no causal relationship between listening to a podcast and exam scores, the only open paths are <em>backdoor</em> paths, these two confounding pathways.</p>
</div>
</section>
<section id="dags---open-paths-1" class="slide level2">
<h2>DAGs - open paths</h2>
<div style="font-size: 75%">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a>podcast_dag <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a></a>  <span class="co"># show the whole dag as a light gray shadow rather than just the paths</span></span>
<span id="cb5-3"><a></a>  ggdag<span class="sc">::</span><span class="fu">ggdag_paths</span>(<span class="at">shadow =</span> <span class="cn">TRUE</span>, <span class="at">text =</span> <span class="cn">FALSE</span>, <span class="at">use_labels =</span> <span class="st">"label"</span>) <span class="sc">+</span></span>
<span id="cb5-4"><a></a>  ggdag<span class="sc">::</span><span class="fu">theme_dag</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-paths-podcast" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-paths-podcast-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-paths-podcast-1.png" width="960">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-paths-podcast-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: <code>ggdag_paths()</code> visualizes open paths in a DAG. There are two open paths in <code>podcast_dag</code>: the fork from <code>mood</code> and the fork from <code>prepared</code>.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="dags---open-paths-2" class="slide level2">
<h2>DAGs - open paths</h2>
<div class="columns">
<div class="column" style="font-size: 65%">
<p>DAGs are not pure data frames, but you can retrieve either the <code>dataframe</code> or <code>dagitty</code> object to work with them directly using <code>pull_dag_data()</code> or <code>pull_dag()</code>. <code>pull_dag()</code> can be useful when you want to work with dagitty functions:</p>
<p><code>ggdag::tidy_dagitty()</code></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a>podcast_dag_tidy <span class="ot">&lt;-</span> podcast_dag <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a></a>  ggdag<span class="sc">::</span><span class="fu">tidy_dagitty</span>()</span>
<span id="cb6-3"><a></a></span>
<span id="cb6-4"><a></a>podcast_dag_tidy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A DAG with 5 nodes and 5 edges
#
# Exposure: podcast
# Outcome: exam
#
# A tibble: 7 × 9
  name         x     y direction to       xend  yend
  &lt;chr&gt;    &lt;int&gt; &lt;int&gt; &lt;fct&gt;     &lt;chr&gt;   &lt;int&gt; &lt;int&gt;
1 exam         3     0 &lt;NA&gt;      &lt;NA&gt;       NA    NA
2 humor        1     0 -&gt;        podcast     2     0
3 mood         1     1 -&gt;        exam        3     0
4 mood         1     1 -&gt;        podcast     2     0
5 podcast      2     0 &lt;NA&gt;      &lt;NA&gt;       NA    NA
6 prepared     1    -1 -&gt;        exam        3     0
7 prepared     1    -1 -&gt;        podcast     2     0
# ℹ 2 more variables: circular &lt;lgl&gt;, label &lt;chr&gt;</code></pre>
</div>
</div>
</div><div class="column" style="font-size: 65%">
<p><code>ggdag::dag_paths()</code></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a>podcast_dag_tidy <span class="sc">|&gt;</span> </span>
<span id="cb8-2"><a></a>  ggdag<span class="sc">::</span><span class="fu">dag_paths</span>() <span class="sc">|&gt;</span> </span>
<span id="cb8-3"><a></a>  <span class="fu">filter</span>(set <span class="sc">==</span> <span class="dv">2</span>, path <span class="sc">==</span> <span class="st">"open path"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A DAG with 3 nodes and 2 edges
#
# Exposure: podcast
# Outcome: exam
#
# A tibble: 4 × 11
  set   name        x     y direction to     xend  yend
  &lt;chr&gt; &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;fct&gt;     &lt;chr&gt; &lt;int&gt; &lt;int&gt;
1 2     exam        3     0 &lt;NA&gt;      &lt;NA&gt;     NA    NA
2 2     podcast     2     0 &lt;NA&gt;      &lt;NA&gt;     NA    NA
3 2     prepar…     1    -1 -&gt;        exam      3     0
4 2     prepar…     1    -1 -&gt;        podc…     2     0
# ℹ 3 more variables: circular &lt;lgl&gt;, label &lt;chr&gt;,
#   path &lt;chr&gt;</code></pre>
</div>
</div>
<p><code>ggdag::pull_dag()</code></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a>podcast_dag_tidy <span class="sc">|&gt;</span> </span>
<span id="cb10-2"><a></a>  ggdag<span class="sc">::</span><span class="fu">pull_dag</span>() <span class="sc">|&gt;</span> </span>
<span id="cb10-3"><a></a>  dagitty<span class="sc">::</span><span class="fu">paths</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$paths
[1] "podcast &lt;- mood -&gt; exam"    
[2] "podcast &lt;- prepared -&gt; exam"

$open
[1] TRUE TRUE</code></pre>
</div>
</div>
</div></div>
</section>
<section id="dags---open-paths-3" class="slide level2">
<h2>DAGs - open paths</h2>
<div class="columns">
<div class="column" style="font-size: 65%">
<p><code>ggdag::ggdag_adjustment_set()</code> visualizes any valid adjustment sets implied by the DAG. Figure 5.11 shows adjusted variables as squares. Any arrows coming out of adjusted variables are removed from the DAG because the path is longer open at that variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a>ggdag<span class="sc">::</span><span class="fu">ggdag_adjustment_set</span>(</span>
<span id="cb12-2"><a></a>  podcast_dag, </span>
<span id="cb12-3"><a></a>  <span class="at">text =</span> <span class="cn">FALSE</span>, </span>
<span id="cb12-4"><a></a>  <span class="at">use_labels =</span> <span class="st">"label"</span></span>
<span id="cb12-5"><a></a>) <span class="sc">+</span> ggdag<span class="sc">::</span><span class="fu">theme_dag</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div><div class="column" style="font-size: 75%">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-podcast-adustment-set" class="quarto-float quarto-figure quarto-figure-center" data-fig-align="center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-podcast-adustment-set-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-podcast-adustment-set-1.png" class="quarto-figure quarto-figure-center" width="384">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-podcast-adustment-set-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: A visualization of the minimal adjustment set for the podcast-exam DAG. If this DAG is correct, two variables are required to block the backdoor paths: <code>mood</code> and <code>prepared</code>.
</figcaption>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="dags---open-paths-4" class="slide level2">
<h2>DAGs - open paths</h2>
<div style="font-size: 75%">
<p><a href="#/fig-podcast-adustment-set" class="quarto-xref">Figure&nbsp;6</a> shows the <em>minimal adjustment set</em>. By default, ggdag returns the set(s) that can close all backdoor paths with the fewest number of variables possible.</p>
<p>In this DAG, that’s just one set: <code>mood</code> and <code>prepared</code>. This set makes sense because there are two backdoor paths, and the only other variables on them besides the exposure and outcome are these two variables.</p>
<p>So, at minimum, we must account for both to get a valid estimate.</p>
<p>Minimal adjustment sets are only one type of valid adjustment set. Sometimes, other combinations of variables can get us an unbiased effect estimate. Two other options available in ggdag are full adjustment sets and canonical adjustment sets. Full adjustment sets are every combination of variables that result in a valid set.</p>
</div>
</section>
<section id="dags---open-paths-5" class="slide level2">
<h2>DAGs - open paths</h2>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a>ggdag<span class="sc">::</span><span class="fu">ggdag_adjustment_set</span>(</span>
<span id="cb13-2"><a></a>  podcast_dag, </span>
<span id="cb13-3"><a></a>  <span class="at">text =</span> <span class="cn">FALSE</span>, </span>
<span id="cb13-4"><a></a>  <span class="at">use_labels =</span> <span class="st">"label"</span>,</span>
<span id="cb13-5"><a></a>  <span class="co"># get full adjustment sets</span></span>
<span id="cb13-6"><a></a>  <span class="at">type =</span> <span class="st">"all"</span></span>
<span id="cb13-7"><a></a>) <span class="sc">+</span> ggdag<span class="sc">::</span><span class="fu">theme_dag</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-adustment-set-all-1.png" class="quarto-figure quarto-figure-center r-stretch" width="912" id="fig-adustment-set-all"><p class="caption">
Figure&nbsp;7: All valid adjustment sets for <code>podcast_dag</code>.
</p></section>
<section id="dags---open-paths-example" class="slide level2">
<h2>DAGs - open paths: example</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a><span class="fu">set.seed</span>(<span class="dv">8740</span>)</span>
<span id="cb14-2"><a></a>sim_data <span class="ot">&lt;-</span> podcast_dag <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a></a>  ggdag<span class="sc">::</span><span class="fu">simulate_data</span>()</span>
<span id="cb14-4"><a></a>sim_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 500 × 5
     exam  humor    mood podcast prepared
    &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
 1  0.687  0.529  0.0451  0.0784  -0.477 
 2  0.743  1.23  -0.235   2.28    -1.34  
 3  0.906 -0.615 -0.778  -1.36    -0.839 
 4  0.487  0.756 -0.187  -1.12     0.461 
 5 -2.39   1.00  -0.0725 -1.02     1.81  
 6  0.519 -1.42  -0.0496 -1.08    -0.429 
 7 -0.178  0.321 -0.560   0.594    0.193 
 8  0.424  0.196 -0.435  -0.396    0.618 
 9  0.972  1.98  -2.06    0.990    1.40  
10 -0.595 -1.66   0.215  -2.20    -0.0223
# ℹ 490 more rows</code></pre>
</div>
</div>
</section>
<section id="dags---open-paths-example-1" class="slide level2">
<h2>DAGs - open paths: example</h2>
<div class="columns">
<div class="column" style="font-size: 65%">
<p>Since we have simulated this data, we know that this is a case where <em>standard methods will succeed</em> and, therefore, can estimate the causal effect using a basic linear regression model.</p>
<p><a href="#/fig-dag-sim" class="quarto-xref">Figure&nbsp;8</a> (Estimates tab) shows a forest plot of the simulated data based on our DAG. Notice the model that only included the exposure resulted in a spurious effect (an estimate of &gt;0.1 when we know the truth is 0).</p>
<p>By contrast, the model that adjusted for the two variables as suggested by <code>ggdag_adjustment_set()</code> is not spurious (much closer to 0).</p>
</div><div class="column" style="font-size: 65%">
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a><span class="do">## Model that does not close backdoor paths</span></span>
<span id="cb16-2"><a></a>unadjusted_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(exam <span class="sc">~</span> podcast, sim_data) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(<span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-4"><a></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"podcast"</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-5"><a></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">formula =</span> <span class="st">"podcast"</span>)</span>
<span id="cb16-6"><a></a></span>
<span id="cb16-7"><a></a><span class="do">## Model that closes backdoor paths</span></span>
<span id="cb16-8"><a></a>adjusted_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(exam <span class="sc">~</span> podcast <span class="sc">+</span> mood <span class="sc">+</span> prepared, sim_data) <span class="sc">|&gt;</span></span>
<span id="cb16-9"><a></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(<span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-10"><a></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"podcast"</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-11"><a></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">formula =</span> <span class="st">"podcast + mood + prepared"</span>)</span>
<span id="cb16-12"><a></a></span>
<span id="cb16-13"><a></a>dplyr<span class="sc">::</span><span class="fu">bind_rows</span>(</span>
<span id="cb16-14"><a></a>  unadjusted_model,</span>
<span id="cb16-15"><a></a>  adjusted_model</span>
<span id="cb16-16"><a></a>) <span class="sc">|&gt;</span></span>
<span id="cb16-17"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> estimate, <span class="at">y =</span> formula, <span class="at">xmin =</span> conf.low, <span class="at">xmax =</span> conf.high)) <span class="sc">+</span></span>
<span id="cb16-18"><a></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"grey80"</span>) <span class="sc">+</span></span>
<span id="cb16-19"><a></a>  <span class="fu">geom_pointrange</span>(<span class="at">fatten =</span> <span class="dv">3</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb16-20"><a></a>  <span class="fu">theme_minimal</span>(<span class="dv">18</span>) <span class="sc">+</span></span>
<span id="cb16-21"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb16-22"><a></a>    <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb16-23"><a></a>    <span class="at">caption =</span> <span class="st">"correct effect size: 0"</span></span>
<span id="cb16-24"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-dag-sim" class="quarto-float quarto-figure quarto-figure-center" data-fig-align="center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-dag-sim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-dag-sim-1.png" class="quarto-figure quarto-figure-center" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dag-sim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Forest plot of simulated data based on the DAG described in <a href="#/fig-dag-podcast" class="quarto-xref">Figure&nbsp;4</a>.
</figcaption>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="dags---advanced-confounding" class="slide level2">
<h2>DAGs - advanced confounding</h2>
<div style="font-size: 70%">
<p>In <code>podcast_dag</code>, <code>mood</code> and <code>prepared</code> were <em>direct</em> confounders: an arrow was going directly from them to <code>podcast</code> and <code>exam</code>.</p>
<p>Often, backdoor paths are more complex. For example, let’s add two new variables: <code>alertness</code> and <code>skills_course</code>. <code>alertness</code> represents the feeling of alertness from a good mood, thus an arrow from <code>mood</code> to <code>alertness</code>. <code>skills_course</code> represents whether the student took a College Skills Course and learned time management techniques.</p>
<p>Now, <code>skills_course</code> is what frees up the time to listen to a podcast as well as being prepared for the exam. <code>mood</code> and <code>prepared</code> are no longer direct confounders: they are two variables along a more complex backdoor path. Additionally, we’ve added an arrow going from <code>humor</code> to <code>mood</code>.</p>
</div>
</section>
<section id="dags---advanced-confounding-1" class="slide level2">
<h2>DAGs - advanced confounding</h2>
<div style="font-size: 70%">
<p>Let’s take a look at <a href="#/fig-podcast_dag2" class="quarto-xref">Figure&nbsp;9</a>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a>podcast_dag2 <span class="ot">&lt;-</span> ggdag<span class="sc">::</span><span class="fu">dagify</span>(</span>
<span id="cb17-2"><a></a>    podcast <span class="sc">~</span> mood <span class="sc">+</span> humor <span class="sc">+</span> skills_course,</span>
<span id="cb17-3"><a></a>    alertness <span class="sc">~</span> mood,</span>
<span id="cb17-4"><a></a>    mood <span class="sc">~</span> humor,</span>
<span id="cb17-5"><a></a>    prepared <span class="sc">~</span> skills_course,</span>
<span id="cb17-6"><a></a>    exam <span class="sc">~</span> alertness <span class="sc">+</span> prepared,</span>
<span id="cb17-7"><a></a>    <span class="at">coords =</span> ggdag<span class="sc">::</span><span class="fu">time_ordered_coords</span>(),</span>
<span id="cb17-8"><a></a>    <span class="at">exposure =</span> <span class="st">"podcast"</span>,</span>
<span id="cb17-9"><a></a>    <span class="at">outcome =</span> <span class="st">"exam"</span>,</span>
<span id="cb17-10"><a></a>    <span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb17-11"><a></a>        <span class="at">podcast =</span> <span class="st">"podcast"</span>,</span>
<span id="cb17-12"><a></a>        <span class="at">exam =</span> <span class="st">"exam score"</span>,</span>
<span id="cb17-13"><a></a>        <span class="at">mood =</span> <span class="st">"mood"</span>,</span>
<span id="cb17-14"><a></a>        <span class="at">alertness =</span> <span class="st">"alertness"</span>,</span>
<span id="cb17-15"><a></a>        <span class="at">skills_course =</span> <span class="st">"college</span><span class="sc">\n</span><span class="st">skills course"</span>,</span>
<span id="cb17-16"><a></a>        <span class="at">humor =</span> <span class="st">"humor"</span>,</span>
<span id="cb17-17"><a></a>        <span class="at">prepared =</span> <span class="st">"prepared"</span></span>
<span id="cb17-18"><a></a>    )</span>
<span id="cb17-19"><a></a>)</span>
<span id="cb17-20"><a></a></span>
<span id="cb17-21"><a></a>ggdag<span class="sc">::</span><span class="fu">ggdag</span>(podcast_dag2, <span class="at">use_labels =</span> <span class="st">"label"</span>, <span class="at">text =</span> <span class="cn">FALSE</span>)  <span class="sc">+</span> </span>
<span id="cb17-22"><a></a>  ggdag<span class="sc">::</span><span class="fu">theme_dag</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-podcast_dag2" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-podcast_dag2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-podcast_dag2-1.png" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-podcast_dag2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: An expanded version of <code>podcast_dag</code> that includes two additional variables: <code>skills_course</code>, representing a College Skills Course, and <code>alertness</code>.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="dags---advanced-confounding-2" class="slide level2">
<h2>DAGs - advanced confounding</h2>
<div style="font-size: 65%">
<p>Now there are <em>three</em> backdoor paths we need to close: <code>podcast &lt;- humor -&gt; mood -&gt; alertness -&gt; exam</code>, <code>podcast &lt;- mood -&gt; alertness -&gt; exam</code>, and <code>podcast &lt;- skills_course -&gt; prepared -&gt; exam</code>.</p>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">code</a></li><li><a href="#tabset-1-2">paths</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a>ggdag<span class="sc">::</span><span class="fu">ggdag_paths</span>(podcast_dag2, <span class="at">use_labels =</span> <span class="st">"label"</span>, <span class="at">text =</span> <span class="cn">FALSE</span>, <span class="at">shadow =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> </span>
<span id="cb18-2"><a></a>  ggdag<span class="sc">::</span><span class="fu">theme_dag</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-1-2">
<div class="cell">
<div class="cell-output-display">
<div id="fig-podcast_dag2-paths" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-podcast_dag2-paths-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-podcast_dag2-paths-1.png" width="1056">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-podcast_dag2-paths-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Three open paths in <code>podcast_dag2</code>. Since there is no effect of <code>podcast</code> on <code>exam</code>, all three are backdoor paths that must be closed to get the correct effect.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="dags---advanced-confounding-3" class="slide level2">
<h2>DAGs - advanced confounding</h2>
<div style="font-size: 75%">
<p>There are four minimal adjustment sets to close all three paths (and eighteen full adjustment sets!). The minimal adjustment sets are <code>alertness + prepared</code>, <code>alertness + skills_course</code>, <code>mood + prepared</code>, <code>mood + skills_course</code>.</p>
<p>We can now block the open paths in several ways - <code>mood</code> and <code>prepared</code> still work, but we’ve got other options now.</p>
<p>Notably, <code>prepared</code> and <code>alertness</code> could happen at the same time or even after <code>podcast</code>. <code>skills_course</code> and <code>mood</code> still happen before both <code>podcast</code> and <code>exam</code>, so the idea is still the same: the confounding pathway starts before the exposure and outcome.</p>
<p>The next slide shows the result of executing the following code:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a>ggdag<span class="sc">::</span><span class="fu">ggdag_adjustment_set</span>(podcast_dag2, <span class="at">use_labels =</span> <span class="st">"label"</span>, <span class="at">text =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="dags---advanced-confounding-4" class="slide level2">
<h2>DAGs - advanced confounding</h2>
<div style="font-size: 75%">
<div class="cell">
<div class="cell-output-display">
<div id="fig-podcast_dag2-set" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-podcast_dag2-set-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-podcast_dag2-set-1.png" width="1056">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-podcast_dag2-set-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Valid minimal adjustment sets that will close the backdoor paths in <a href="#/fig-podcast_dag2-paths" class="quarto-xref">Figure&nbsp;10</a>.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="dags---advanced-confounding-5" class="slide level2">
<h2>DAGs - advanced confounding</h2>
<div style="font-size: 65%">
<p>Deciding between these adjustment sets is a matter of judgment: if all data are perfectly measured, the DAG is correct, and we’ve modeled them correctly, then it doesn’t matter which we use. Each adjustment set will result in an unbiased estimate.</p>
<p>All three of those assumptions are usually untrue to some degree. Let’s consider the path via <code>skills_course</code> and <code>prepared</code>.</p>
<p>It may be that we are better able to assess whether or not someone took the College Skills Course than how prepared for the exam they are. In that case, an adjustment set with <code>skills_course</code> is a better option.</p>
<p>But perhaps we better understand the relationship between preparedness and exam results. If we have it measured, controlling for that might be better. We could get the best of both worlds by including both variables: between the better measurement of <code>skills_course</code> and the better modeling of <code>prepared</code>, we might have a better chance of minimizing confounding from this path.</p>
</div>
</section>
<section id="dags---selection-bias" class="slide level2">
<h2>DAGs - selection bias</h2>
<div style="font-size: 65%">
<p>Selection bias is another name for the type of bias that is induced by adjusting for a collider. It’s called “selection bias” because a common form of collider-induced bias is a variable inherently stratified upon by the design of the study—selection <em>into</em> the study.</p>
<p>Let’s consider a case based on the original <code>podcast_dag</code> but with one additional variable: whether or not the student showed up to the exam.</p>
<p>Now, there is an indirect effect of <code>podcast</code> on <code>exam</code>: listening to a podcast influences whether or not the students attend the exam. The true result of <code>exam</code> is missing for those who didn’t show up; by studying the group of people who <em>did</em> show up, we are inherently stratifying on this variable.</p>
</div>
</section>
<section id="dags---selection-bias-1" class="slide level2">
<h2>DAGs - selection bias</h2>
<div style="font-size: 75%">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a>podcast_dag3 <span class="ot">&lt;-</span> ggdag<span class="sc">::</span><span class="fu">dagify</span>(</span>
<span id="cb20-2"><a></a>  podcast <span class="sc">~</span> mood <span class="sc">+</span> humor <span class="sc">+</span> prepared,</span>
<span id="cb20-3"><a></a>  exam <span class="sc">~</span> mood <span class="sc">+</span> prepared <span class="sc">+</span> showed_up,</span>
<span id="cb20-4"><a></a>  showed_up <span class="sc">~</span> podcast <span class="sc">+</span> mood <span class="sc">+</span> prepared,</span>
<span id="cb20-5"><a></a>  <span class="at">coords =</span> ggdag<span class="sc">::</span><span class="fu">time_ordered_coords</span>(</span>
<span id="cb20-6"><a></a>    <span class="fu">list</span>(</span>
<span id="cb20-7"><a></a>      <span class="co"># time point 1</span></span>
<span id="cb20-8"><a></a>      <span class="fu">c</span>(<span class="st">"prepared"</span>, <span class="st">"humor"</span>, <span class="st">"mood"</span>), </span>
<span id="cb20-9"><a></a>      <span class="co"># time point 2</span></span>
<span id="cb20-10"><a></a>      <span class="st">"podcast"</span>,  </span>
<span id="cb20-11"><a></a>      <span class="st">"showed_up"</span>,  </span>
<span id="cb20-12"><a></a>      <span class="co"># time point 3</span></span>
<span id="cb20-13"><a></a>      <span class="st">"exam"</span></span>
<span id="cb20-14"><a></a>    )</span>
<span id="cb20-15"><a></a>  ),</span>
<span id="cb20-16"><a></a>  <span class="at">exposure =</span> <span class="st">"podcast"</span>,</span>
<span id="cb20-17"><a></a>  <span class="at">outcome =</span> <span class="st">"exam"</span>,</span>
<span id="cb20-18"><a></a>  <span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb20-19"><a></a>    <span class="at">podcast =</span> <span class="st">"podcast"</span>,</span>
<span id="cb20-20"><a></a>    <span class="at">exam =</span> <span class="st">"exam score"</span>,</span>
<span id="cb20-21"><a></a>    <span class="at">mood =</span> <span class="st">"mood"</span>,</span>
<span id="cb20-22"><a></a>    <span class="at">humor =</span> <span class="st">"humor"</span>,</span>
<span id="cb20-23"><a></a>    <span class="at">prepared =</span> <span class="st">"prepared"</span>,</span>
<span id="cb20-24"><a></a>    <span class="at">showed_up =</span> <span class="st">"showed up"</span></span>
<span id="cb20-25"><a></a>  )</span>
<span id="cb20-26"><a></a>)</span>
<span id="cb20-27"><a></a>ggdag<span class="sc">::</span><span class="fu">ggdag</span>(podcast_dag3, <span class="at">use_labels =</span> <span class="st">"label"</span>, <span class="at">text =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb20-28"><a></a>  ggdag<span class="sc">::</span><span class="fu">theme_dag</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-podcast_dag3" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-podcast_dag3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-podcast_dag3-1.png" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-podcast_dag3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Another variant of <code>podcast_dag</code>, this time including the inherent stratification on those who appear for the exam. There is still no direct effect of <code>podcast</code> on <code>exam</code>, but there is an indirect effect via <code>showed_up</code>.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="dags---selection-bias-2" class="slide level2">
<h2>DAGs - selection bias</h2>
<div style="font-size: 75%">
<p>The problem is that <code>showed_up</code> is both a collider and a mediator: stratifying on it induces a relationship between many of the variables in the DAG but blocks the indirect effect of <code>podcast</code> on <code>exam</code>.</p>
<p>Luckily, the adjustment sets can handle the first problem; because <code>showed_up</code> happens <em>before</em> <code>exam</code>, we’re less at risk of collider bias between the exposure and outcome.</p>
<p>Unfortunately, we cannot calculate the total effect of <code>podcast</code> on <code>exam</code> because part of the effect is missing: the indirect effect is closed at <code>showed_up</code>.</p>
</div>
</section>
<section id="dags---selection-bias-3" class="slide level2">
<h2>DAGs - selection bias</h2>
<div style="font-size: 75%">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a>podcast_dag3 <span class="sc">|&gt;</span> </span>
<span id="cb21-2"><a></a>  ggdag<span class="sc">::</span><span class="fu">adjust_for</span>(<span class="st">"showed_up"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb21-3"><a></a>  ggdag<span class="sc">::</span><span class="fu">ggdag_adjustment_set</span>(<span class="at">text =</span> <span class="cn">FALSE</span>, <span class="at">use_labels =</span> <span class="st">"label"</span>) <span class="sc">+</span> </span>
<span id="cb21-4"><a></a>  ggdag<span class="sc">::</span><span class="fu">theme_dag</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-podcast_dag3-as" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-podcast_dag3-as-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-podcast_dag3-as-1.png" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-podcast_dag3-as-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: The adjustment set for <code>podcast_dag3</code> given that the data are inherently conditioned on showing up to the exam. In this case, there is no way to recover an unbiased estimate of the total effect of <code>podcast</code> on <code>exam</code>.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="dags---selection-bias-4" class="slide level2">
<h2>DAGs - selection bias</h2>
<div class="columns">
<div class="column" style="font-size: 60%">
<p>Sometimes, you can still estimate effects in this situation by changing the estimate you wish to calculate. We can’t calculate the total effect because we are missing the indirect effect, but we can still calculate the direct effect of <code>podcast</code> on <code>exam</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a>podcast_dag3 <span class="sc">|&gt;</span> </span>
<span id="cb22-2"><a></a>  ggdag<span class="sc">::</span><span class="fu">adjust_for</span>(<span class="st">"showed_up"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb22-3"><a></a>  ggdag<span class="sc">::</span><span class="fu">ggdag_adjustment_set</span>(</span>
<span id="cb22-4"><a></a>    <span class="at">effect =</span> <span class="st">"direct"</span></span>
<span id="cb22-5"><a></a>    , <span class="at">text =</span> <span class="cn">FALSE</span></span>
<span id="cb22-6"><a></a>    , <span class="at">use_labels =</span> <span class="st">"label"</span></span>
<span id="cb22-7"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div><div class="column" style="font-size: 60%">
<div class="cell">
<div class="cell-output-display">
<div id="fig-podcast_dag3-direct" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-podcast_dag3-direct-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-podcast_dag3-direct-1.png" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-podcast_dag3-direct-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: The adjustment set for <code>podcast_dag3</code> when targeting a different effect. There is one minimal adjustment set that we can use to estimate the direct effect of <code>podcast</code> on <code>exam</code>.
</figcaption>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="dags---m-bias-and-butterfly-bias" class="slide level2">
<h2>DAGs - M-Bias and Butterfly Bias</h2>
<div class="columns">
<div class="column" style="font-size: 60%">
<p>A particular case of selection bias that you’ll often see is <em>M-bias</em>. It’s called M-bias because it looks like an M when arranged top to bottom.</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>ggdag has several quick-DAGs for demonstrating basic causal structures, including <code>confounder_triangle()</code>, <code>collider_triangle()</code>, <code>m_bias()</code>, and <code>butterfly_bias()</code>.</p>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a>dagitty<span class="sc">::</span><span class="fu">paths</span>( ggdag<span class="sc">::</span><span class="fu">m_bias</span>() )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$paths
[1] "x &lt;- a -&gt; m &lt;- b -&gt; y"

$open
[1] FALSE</code></pre>
</div>
</div>
</div><div class="column" style="font-size: 60%">
<div class="cell">
<div class="cell-output-display">
<div id="fig-m-bias" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-m-bias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-m-bias-1.png" width="384">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-m-bias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: A DAG representing M-Bias, a situation where a collider predates the exposure and outcome.
</figcaption>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="dags---m-bias-and-butterfly-bias-1" class="slide level2">
<h2>DAGs - M-Bias and Butterfly Bias</h2>
<div style="font-size: 75%">
<p>Let’s focus on the <code>mood</code> path of the podcast-exam DAG.</p>
<p>What if we were wrong about mood, and the actual relationship was M-shaped? Let’s say that, rather than causing <code>podcast</code> and <code>exam</code>, <code>mood</code> was itself caused by two mutual causes of <code>podcast</code> and <code>exam</code>, <code>u1</code> and <code>u2</code>.</p>
<p>We don’t know what <code>u1</code> and <code>u2</code> are, and we don’t have them measured. As above, there are no open paths in this subset of the DAG.</p>
</div>
</section>
<section id="dags---m-bias-and-butterfly-bias-2" class="slide level2">
<h2>DAGs - M-Bias and Butterfly Bias</h2>
<div style="font-size: 75%">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a>podcast_dag4 <span class="ot">&lt;-</span> ggdag<span class="sc">::</span><span class="fu">dagify</span>(</span>
<span id="cb25-2"><a></a>  podcast <span class="sc">~</span> u1,</span>
<span id="cb25-3"><a></a>  exam <span class="sc">~</span> u2,</span>
<span id="cb25-4"><a></a>  mood <span class="sc">~</span> u1 <span class="sc">+</span> u2,</span>
<span id="cb25-5"><a></a>  <span class="at">coords =</span> <span class="fu">time_ordered_coords</span>(<span class="fu">list</span>(</span>
<span id="cb25-6"><a></a>    <span class="fu">c</span>(<span class="st">"u1"</span>, <span class="st">"u2"</span>),</span>
<span id="cb25-7"><a></a>    <span class="st">"mood"</span>,</span>
<span id="cb25-8"><a></a>    <span class="st">"podcast"</span>, </span>
<span id="cb25-9"><a></a>    <span class="st">"exam"</span></span>
<span id="cb25-10"><a></a>  )),</span>
<span id="cb25-11"><a></a>  <span class="at">exposure =</span> <span class="st">"podcast"</span>,</span>
<span id="cb25-12"><a></a>  <span class="at">outcome =</span> <span class="st">"exam"</span>,</span>
<span id="cb25-13"><a></a>  <span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb25-14"><a></a>    <span class="at">podcast =</span> <span class="st">"podcast"</span>,</span>
<span id="cb25-15"><a></a>    <span class="at">exam =</span> <span class="st">"exam score"</span>,</span>
<span id="cb25-16"><a></a>    <span class="at">mood =</span> <span class="st">"mood"</span>,</span>
<span id="cb25-17"><a></a>    <span class="at">u1 =</span> <span class="st">"unmeasured_1"</span>,</span>
<span id="cb25-18"><a></a>    <span class="at">u2 =</span> <span class="st">"unmeasured_2"</span></span>
<span id="cb25-19"><a></a>  ),</span>
<span id="cb25-20"><a></a>  <span class="co"># we don't have them measured</span></span>
<span id="cb25-21"><a></a>  <span class="at">latent =</span> <span class="fu">c</span>(<span class="st">"u1"</span>, <span class="st">"u2"</span>)</span>
<span id="cb25-22"><a></a>)</span>
<span id="cb25-23"><a></a></span>
<span id="cb25-24"><a></a>ggdag<span class="sc">::</span><span class="fu">ggdag</span>(podcast_dag4, <span class="at">use_labels =</span> <span class="st">"label"</span>, <span class="at">text =</span> <span class="cn">FALSE</span>)  <span class="sc">+</span> </span>
<span id="cb25-25"><a></a>  ggdag<span class="sc">::</span><span class="fu">theme_dag</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-podcast_dag4" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-podcast_dag4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-podcast_dag4-1.png" width="528">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-podcast_dag4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: A reconfiguration of <a href="#/fig-dag-podcast" class="quarto-xref">Figure&nbsp;4</a> where <code>mood</code> is a collider on an M-shaped path.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="dags---m-bias-and-butterfly-bias-3" class="slide level2">
<h2>DAGs - M-Bias and Butterfly Bias</h2>
<div class="columns">
<div class="column" style="font-size: 75%">
<p>The problem arises when we think our original DAG is the right DAG: <code>mood</code> is in the adjustment set, so we control for it. But this induces bias!</p>
<p>It opens up a path between <code>u1</code> and <code>u2</code>, thus creating a path from <code>podcast</code> to <code>exam</code>.</p>
<p>If we had either <code>u1</code> or <code>u2</code> measured, we could adjust for them to close this path, but we don’t. There is no way to close this open path.</p>
</div><div class="column" style="font-size: 75%">
<div class="cell">
<div class="cell-output-display">
<div id="fig-podcast_dag4-as" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-podcast_dag4-as-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-podcast_dag4-as-1.png" width="528">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-podcast_dag4-as-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: The adjustment set where <code>mood</code> is a collider. If we control for <code>mood</code> and don’t know about or have the unmeasured causes of <code>mood</code>, we have no means of closing the backdoor path opened by adjusting for a collider.
</figcaption>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="dags---one-of-exposure-outcome" class="slide level2">
<h2>DAGs - One of exposure / outcome</h2>
<p>Let’s consider one other type of causal structure that’s important: causes of the exposure and not the outcome, and their opposites, causes of the outcome and not the exposure.</p>
<p>Let’s add a variable, <code>grader_mood</code>, to the original DAG.</p>
</section>
<section id="dags---one-of-exposure-outcome-1" class="slide level2">
<h2>DAGs - One of exposure / outcome</h2>
<div style="font-size: 75%">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a>podcast_dag5 <span class="ot">&lt;-</span> ggdag<span class="sc">::</span><span class="fu">dagify</span>(</span>
<span id="cb26-2"><a></a>  podcast <span class="sc">~</span> mood <span class="sc">+</span> humor <span class="sc">+</span> prepared,</span>
<span id="cb26-3"><a></a>  exam <span class="sc">~</span> mood <span class="sc">+</span> prepared <span class="sc">+</span> grader_mood,</span>
<span id="cb26-4"><a></a>  <span class="at">coords =</span> ggdag<span class="sc">::</span><span class="fu">time_ordered_coords</span>(</span>
<span id="cb26-5"><a></a>    <span class="fu">list</span>(</span>
<span id="cb26-6"><a></a>      <span class="co"># time point 1</span></span>
<span id="cb26-7"><a></a>      <span class="fu">c</span>(<span class="st">"prepared"</span>, <span class="st">"humor"</span>, <span class="st">"mood"</span>), </span>
<span id="cb26-8"><a></a>      <span class="co"># time point 2</span></span>
<span id="cb26-9"><a></a>      <span class="fu">c</span>(<span class="st">"podcast"</span>, <span class="st">"grader_mood"</span>),  </span>
<span id="cb26-10"><a></a>      <span class="co"># time point 3</span></span>
<span id="cb26-11"><a></a>      <span class="st">"exam"</span></span>
<span id="cb26-12"><a></a>    )</span>
<span id="cb26-13"><a></a>  ),</span>
<span id="cb26-14"><a></a>  <span class="at">exposure =</span> <span class="st">"podcast"</span>,</span>
<span id="cb26-15"><a></a>  <span class="at">outcome =</span> <span class="st">"exam"</span>,</span>
<span id="cb26-16"><a></a>  <span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb26-17"><a></a>    <span class="at">podcast =</span> <span class="st">"podcast"</span>,</span>
<span id="cb26-18"><a></a>    <span class="at">exam =</span> <span class="st">"exam score"</span>,</span>
<span id="cb26-19"><a></a>    <span class="at">mood =</span> <span class="st">"student</span><span class="sc">\n</span><span class="st">mood"</span>,</span>
<span id="cb26-20"><a></a>    <span class="at">humor =</span> <span class="st">"humor"</span>,</span>
<span id="cb26-21"><a></a>    <span class="at">prepared =</span> <span class="st">"prepared"</span>,</span>
<span id="cb26-22"><a></a>    <span class="at">grader_mood =</span> <span class="st">"grader</span><span class="sc">\n</span><span class="st">mood"</span></span>
<span id="cb26-23"><a></a>  )</span>
<span id="cb26-24"><a></a>)</span>
<span id="cb26-25"><a></a>ggdag<span class="sc">::</span><span class="fu">ggdag</span>(podcast_dag5, <span class="at">use_labels =</span> <span class="st">"label"</span>, <span class="at">text =</span> <span class="cn">FALSE</span>)  <span class="sc">+</span> </span>
<span id="cb26-26"><a></a>  ggdag<span class="sc">::</span><span class="fu">theme_dag</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-podcast_dag5" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-podcast_dag5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-podcast_dag5-1.png" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-podcast_dag5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18: A DAG containing a cause of the exposure that is not the cause of the outcome (<code>humor</code>) and a cause of the outcome that is not a cause of the exposure (<code>grader_mood</code>).
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="dags---one-of-exposure-outcome-2" class="slide level2">
<h2>DAGs - One of exposure / outcome</h2>
<div style="font-size: 70%">
<p>Starting with <code>humor</code>:</p>
<p>Variables that cause the exposure but not the outcome are also called <em>instrumental variables</em> (IVs). IVs are an unusual circumstance where, under certain conditions, controlling for them can make other types of bias worse.</p>
<p>What’s unique about this is that IVs can <em>also</em> be used to conduct an entirely different approach to estimating an unbiased effect of the exposure on the outcome. IVs are commonly used this way in econometrics and are increasingly popular in other areas.</p>
<p>In short, IV analysis allows us to estimate the causal effect using a different set of assumptions than the approaches we’ve talked about thus far.</p>
<p>If you’re unsure if the variable is an IV or not, you should probably add it to your model: it’s more likely to be a confounder than an IV, and, it turns out, the bias from adding an IV is usually small in practice. So, like adjusting for a potential M-structure variable, the risk of bias is worse from confounding.</p>
</div>
</section>
<section id="dags---one-of-exposure-outcome-3" class="slide level2">
<h2>DAGs - One of exposure / outcome</h2>
<div style="font-size: 70%">
<p>About variables that are a cause of the outcome but are not the cause of the exposure:</p>
<p>We’ll call them <em>precision variables</em> because we’re concerned about the relationship to the research question at hand, not to another research question where they are exposures.</p>
<p>Like IVs, precision variables do not occur along paths from the exposure to the outcome. Thus, including them is not necessary.</p>
<p>Unlike IVs, including precision variables is beneficial. Including other causes of the outcomes helps a statistical model capture some of its variation.</p>
<p>This doesn’t impact the point estimate of the effect, but it does reduce the variance, resulting in smaller standard errors and narrower confidence intervals. Thus, it’s recommended they be included when possible.</p>
</div>
</section>
<section id="dags---construction" class="slide level2">
<h2>DAGs - Construction</h2>
<div style="font-size: 70%">
<p>In principle, using DAGs is easy: specify the causal relationships you think exist and then query the DAG for information like valid adjustment sets.</p>
<p>In practice, assembling DAGs takes considerable time and thought. Next to defining the research question itself, it’s one of the most challenging steps in making causal inferences.</p>
<p>Very little guidance exists on best practices in assembling DAGs. The next few slides contain some approaches to consider:</p>
</div>
</section>
<section id="dags---construction-1" class="slide level2">
<h2>DAGs - Construction</h2>
<h4 id="iterate-early-and-often">Iterate early and often</h4>
<div style="font-size: 70%">
<p>Make the DAG before you conduct the study, ideally before you even collect the data.</p>
<p>If you’re already working with your data, build your DAG before doing data analysis. Declaring your assumptions ahead of time can help clarify what you need to do, reduce the risk of overfitting (e.g., determining confounders incorrectly from the data), and give you time to get feedback on your DAG.</p>
<p>This last benefit is significant: you should ideally democratize your DAG. Share it early and often with others who are experts on the data, domain, and models.</p>
<p>If you have more than one candidate DAG, check their adjustment sets. If two DAGs have overlapping adjustment sets, focus on those sets; then, you can move forward in a way that satisfies the plausible assumptions you have.</p>
</div>
</section>
<section id="dags---construction-2" class="slide level2">
<h2>DAGs - Construction</h2>
<h4 id="consider-your-question">Consider your question</h4>
<div style="font-size: 70%">
<p>Some questions can be challenging to answer with certain data, while others are more approachable. You should consider precisely what it is you want to estimate.</p>
<p>Another important detail about how your DAG relates to your question is the population and time. Many causal structures are not static over time and space.</p>
<p>The same is true for confounders. Even if something <em>can</em> cause the exposure and outcome, if the prevalence of that thing is zero in the population you’re analyzing, it’s irrelevant to the causal question.</p>
<p>The reverse is also true: something might be unique to the target population.</p>
</div>
</section>
<section id="dags---construction-3" class="slide level2">
<h2>DAGs - Construction</h2>
<h4 id="order-nodes-by-time">Order nodes by time</h4>
<div style="font-size: 70%">
<p>It is recommended to order your variables by time, either left-to-right or up-to-down. There are two reasons for this.</p>
<p>First, time ordering is an integral part of your assumptions. After all, something happening before another thing is a requirement for it to be a cause. Thinking this through carefully will clarify your DAG and the variables you need to address.</p>
<p>Second, after a certain level of complexity, it’s easier to read a DAG when arranged by time because you have to think less about that dimension; it’s inherent to the layout.</p>
<p>The time ordering algorithm in ggdag automates much of this for you, although it’s sometimes helpful to give it more information about the order.</p>
</div>
</section>
<section id="dags---construction-4" class="slide level2">
<h2>DAGs - Construction</h2>
<h4 id="order-nodes-by-time---feedback-loops">Order nodes by time - feedback loops</h4>
<div class="columns">
<div class="column" style="font-size: 70%">
<p>We might think about two things that mutually cause each other as happening in a circle, like global warming and A/C use (A/C use increases global warming, which makes it hotter, which increases A/C use, and so on).</p>
<p>It’s tempting to visualize that relationship like this:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a>ggdag<span class="sc">::</span><span class="fu">dagify</span>(</span>
<span id="cb27-2"><a></a>  ac_use <span class="sc">~</span> global_temp,</span>
<span id="cb27-3"><a></a>  global_temp <span class="sc">~</span> ac_use,</span>
<span id="cb27-4"><a></a>  <span class="at">labels =</span> </span>
<span id="cb27-5"><a></a>    <span class="fu">c</span>(<span class="at">ac_use =</span> <span class="st">"A/C use"</span>, <span class="at">global_temp =</span> <span class="st">"Global</span><span class="sc">\n</span><span class="st">temperature"</span>)</span>
<span id="cb27-6"><a></a>) <span class="sc">|&gt;</span> </span>
<span id="cb27-7"><a></a>  ggdag<span class="sc">::</span><span class="fu">ggdag</span>(</span>
<span id="cb27-8"><a></a>    <span class="at">layout =</span> <span class="st">"circle"</span>, <span class="at">edge_type =</span> <span class="st">"arc"</span>, <span class="at">text =</span> <span class="cn">FALSE</span>, <span class="at">use_labels =</span> <span class="st">"label"</span></span>
<span id="cb27-9"><a></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div><div class="column" style="font-size: 70%">
<div class="cell">
<div class="cell-output-display">
<div id="fig-feedback-loop" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-feedback-loop-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-feedback-loop-1.png" width="432">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-feedback-loop-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;19: A DAG representing the reciprocal relationship between A/C use and global temperature because of global warming. Feedback loops are useful mental shorthands to describe variables that impact each other over time compactly, but they are not true causal diagrams.
</figcaption>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="dags---construction-5" class="slide level2">
<h2>DAGs - Construction</h2>
<h4 id="order-nodes-by-time---feedback-loops-1">Order nodes by time - feedback loops</h4>
<div class="columns">
<div class="column" style="font-size: 70%">
<p>From a DAG perspective, this is a problem because of the <em>A</em> part of <em>DAG</em>: it’s cyclic!</p>
<p>Feedback loops are a shorthand for what really happens, which is that the two variables mutually affect each other <em>over time</em>. Causality only goes forward in time, so it doesn’t make sense to go back and forth like in <a href="#/fig-feedback-loop" class="quarto-xref">Figure&nbsp;19</a>.</p>
<p>The real DAG looks something like this:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a>ggdag<span class="sc">::</span><span class="fu">dagify</span>(</span>
<span id="cb28-2"><a></a>  global_temp_2000 <span class="sc">~</span> ac_use_1990 <span class="sc">+</span> global_temp_1990,</span>
<span id="cb28-3"><a></a>  ac_use_2000 <span class="sc">~</span> ac_use_1990 <span class="sc">+</span> global_temp_1990,</span>
<span id="cb28-4"><a></a>  global_temp_2010 <span class="sc">~</span> ac_use_2000 <span class="sc">+</span> global_temp_2000,</span>
<span id="cb28-5"><a></a>  ac_use_2010 <span class="sc">~</span> ac_use_2000 <span class="sc">+</span> global_temp_2000,</span>
<span id="cb28-6"><a></a>  global_temp_2020 <span class="sc">~</span> ac_use_2010 <span class="sc">+</span> global_temp_2010,</span>
<span id="cb28-7"><a></a>  ac_use_2020 <span class="sc">~</span> ac_use_2010 <span class="sc">+</span> global_temp_2010,</span>
<span id="cb28-8"><a></a>  <span class="at">coords =</span> ggdag<span class="sc">::</span><span class="fu">time_ordered_coords</span>(),</span>
<span id="cb28-9"><a></a>  <span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb28-10"><a></a>    <span class="at">ac_use_1990 =</span> <span class="st">"A/C use</span><span class="sc">\n</span><span class="st">(1990)"</span>, </span>
<span id="cb28-11"><a></a>    <span class="at">global_temp_1990 =</span> <span class="st">"Global</span><span class="sc">\n</span><span class="st">temperature</span><span class="sc">\n</span><span class="st">(1990)"</span>,</span>
<span id="cb28-12"><a></a>    <span class="at">ac_use_2000 =</span> <span class="st">"A/C use</span><span class="sc">\n</span><span class="st">(2000)"</span>, </span>
<span id="cb28-13"><a></a>    <span class="at">global_temp_2000 =</span> <span class="st">"Global</span><span class="sc">\n</span><span class="st">temperature</span><span class="sc">\n</span><span class="st">(2000)"</span>,</span>
<span id="cb28-14"><a></a>    <span class="at">ac_use_2010 =</span> <span class="st">"A/C use</span><span class="sc">\n</span><span class="st">(2010)"</span>, </span>
<span id="cb28-15"><a></a>    <span class="at">global_temp_2010 =</span> <span class="st">"Global</span><span class="sc">\n</span><span class="st">temperature</span><span class="sc">\n</span><span class="st">(2010)"</span>,</span>
<span id="cb28-16"><a></a>    <span class="at">ac_use_2020 =</span> <span class="st">"A/C use</span><span class="sc">\n</span><span class="st">(2020)"</span>, </span>
<span id="cb28-17"><a></a>    <span class="at">global_temp_2020 =</span> <span class="st">"Global</span><span class="sc">\n</span><span class="st">temperature</span><span class="sc">\n</span><span class="st">(2020)"</span></span>
<span id="cb28-18"><a></a>  )</span>
<span id="cb28-19"><a></a>) <span class="sc">|&gt;</span> </span>
<span id="cb28-20"><a></a>  ggdag<span class="sc">::</span><span class="fu">ggdag</span>(<span class="at">text =</span> <span class="cn">FALSE</span>, <span class="at">use_labels =</span> <span class="st">"label"</span>) <span class="sc">+</span> </span>
<span id="cb28-21"><a></a>  ggdag<span class="sc">::</span><span class="fu">theme_dag</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div><div class="column" style="font-size: 70%">
<div class="cell">
<div class="cell-output-display">
<div id="fig-feedforward" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-feedforward-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-feedforward-1.png" width="528">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-feedforward-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20: A DAG showing the relationship between A/C use and global temperature over time. The true causal relationship in a feedback loop goes <em>forward</em>.
</figcaption>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="dags---construction-6" class="slide level2">
<h2>DAGs - Construction</h2>
<h4 id="use-robustness-checks">Use robustness checks</h4>
<div style="font-size: 65%">
<p>Finally, check your DAG for robustness. It is unlikely the correctness of your DAG can be verified, but you can use the implications in your DAG to check the support for it. Some robustness checks:</p>
<ol type="1">
<li><strong>DAG-data consistency</strong>. There are many implications of your DAG. Because blocking a path removes statistical dependencies from that path, you can check those assumptions in several places in your DAG (see <code>dagitty::impliedConditionalIndependencies</code>).</li>
<li><strong>Alternate adjustment sets</strong>. Adjustment sets should give roughly the same answer because, outside of random and measurement errors, they are all sets that block backdoor paths. If more than one adjustment set seems reasonable, you can use that as a sensitivity analysis by checking multiple models.</li>
</ol>
<p>The checks should be complementary to your initial DAG, not a way of <em>replacing</em> it. If you use more than one adjustment set during your analysis, you should report the results from all of them to avoid overfitting your results to your data.</p>
</div>
</section></section>
<section>
<section id="example-mosquito-nets-and-malaria" class="title-slide slide level1 center">
<h1>Example: mosquito nets and malaria</h1>

</section>
<section id="example-steps" class="slide level2">
<h2>Example: steps</h2>
<p>In the remainder of today’s slides, we’ll analyze simulated data using a few key steps</p>
<ol type="1">
<li>Specify a causal question</li>
<li>Draw our assumptions using a causal diagram</li>
<li>Model our assumptions</li>
<li>Diagnose our models</li>
<li>Estimate the causal effect</li>
<li>Conduct sensitivity analysis on the effect estimate</li>
</ol>
</section>
<section id="example-causal-question" class="slide level2">
<h2>Example: causal question</h2>
<div style="font-size: 75%">
<blockquote>
<p>Researchers are interested in whether using mosquito nets decreases an individual’s risk of contracting malaria. They have collected data from 1,752 households in an unnamed country and have variables related to environmental factors, individual health, and household characteristics. The data is <strong>not experimental</strong>—researchers have no control over who uses mosquito nets, and individual households make their own choices over whether to apply for free nets or buy their own nets, as well as whether they use the nets if they have them.</p>
</blockquote>
</div>
</section>
<section id="example-causal-question-1" class="slide level2">
<h2>Example: causal question</h2>
<div style="font-size: 75%">
<ul>
<li><code>id</code> - an ID variable</li>
<li><code>net</code> and <code>net_num</code> - a binary variable indicating if the participant used a net (1) or didn’t use a net (0)</li>
<li><code>malaria_risk</code>- risk of malaria scale ranging from 0-100</li>
<li><code>income</code> - weekly income, measured in dollars</li>
<li><code>health</code> - a health score scale ranging from 0–100</li>
<li><code>household</code> - number of people living in the household</li>
<li><code>eligible</code> - a binary variable indicating if the household is eligible for the free net program.</li>
<li><code>temperature</code> - the average temperature at night, in Celsius</li>
<li><code>resistance</code> - Insecticide resistance of local mosquitoes. A scale of 0–100, with higher values indicating higher resistance.</li>
</ul>
</div>
</section>
<section id="example-causal-question-2" class="slide level2">
<h2>Example: causal question</h2>
<div style="font-size: 75%">
<p>The distribution of malaria risk appears to be quite different by net usage.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-malaria-risk-density" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-malaria-risk-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-malaria-risk-density-1.png" width="720">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-malaria-risk-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21: A density plot of malaria risk for those who did and did not use nets. The average risk of malaria is lower for those who use nets.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="example-causal-question-3" class="slide level2">
<h2>Example: causal question</h2>
<div style="font-size: 75%">
<p>In <a href="#/fig-malaria-risk-density" class="quarto-xref">Figure&nbsp;21</a>, the density of those who used nets is to the left of those who did not use nets. The mean difference in malaria risk is about 16.4, suggesting net use might be protective against malaria.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a>causalworkshop<span class="sc">::</span>net_data <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(net) <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">malaria_risk =</span> <span class="fu">mean</span>(malaria_risk)) <span class="sc">|&gt;</span> </span>
<span id="cb29-4"><a></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">diff =</span> malaria_risk <span class="sc">-</span> dplyr<span class="sc">::</span><span class="fu">lag</span>(malaria_risk))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  net   malaria_risk  diff
  &lt;lgl&gt;        &lt;dbl&gt; &lt;dbl&gt;
1 FALSE         43.9  NA  
2 TRUE          27.5 -16.4</code></pre>
</div>
</div>
<p>And that’s what we see with simple linear regression, as well, as we would expect.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a>causalworkshop<span class="sc">::</span>net_data <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a></a>  <span class="fu">lm</span>(malaria_risk <span class="sc">~</span> net, <span class="at">data =</span> _) <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a></a>  broom<span class="sc">::</span><span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)     43.9     0.377     116.  0       
2 netTRUE        -16.4     0.741     -22.1 1.10e-95</code></pre>
</div>
</div>
</div>
</section>
<section id="example-assumptions-using-a-dag" class="slide level2">
<h2>Example: assumptions using a DAG</h2>
<div style="font-size: 75%">
<p>The problem that we face is that other factors may be responsible for the effect we’re seeing.</p>
<p>In this example, we’ll focus on confounding: a common cause of net usage and malaria will bias the effect we see unless we account for it somehow.</p>
<p>To determine which variables we need to account we’ll use use a causal diagram or DAG, to visualize the assumptions that we’re making about the causal relationships between the exposure, outcome, and other variables we think might be related.</p>
<p>The proposed DAG for this question is one the next slide.</p>
</div>
</section>
<section id="example-assumptions-using-a-dag-1" class="slide level2">
<h2>Example: assumptions using a DAG</h2>
<div style="font-size: 65%">
<div class="cell">
<div class="cell-output-display">
<div id="fig-net-data-dag" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-net-data-dag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-net-data-dag-1.png" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-net-data-dag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22: A proposed causal diagram of the effect of bed net use on malaria. This directed acyclic graph (DAG) states our assumption that bed net use causes a reduction in malaria risk. It also says that we assume: malaria risk is impacted by net usage, income, health, temperature, and insecticide resistance; net usage is impacted by income, health, temperature, eligibility for the free net program, and the number of people in a household; eligibility for the free net programs is impacted by income and the number of people in a household; and health is impacted by income.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="example-assumptions-using-a-dag-2" class="slide level2">
<h2>Example: assumptions using a DAG</h2>
<div style="font-size: 65%">
<div class="cell">
<div class="cell-output-display">
<div id="fig-net-data-confounding" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-net-data-confounding-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-net-data-confounding-1.png" width="1344">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-net-data-confounding-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;23: In the proposed DAG, there are eight open pathways that contribute to the causal effect seen in the naive regression: the true effect (in green) of net usage on malaria risk and seven other confounding pathways (in orange). The naive estimate is wrong because it is a composite of all these effects.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="example-model-our-assumptions" class="slide level2">
<h2>Example: Model our assumptions</h2>
<div style="font-size: 65%">
<p>For this DAG, we need to control for three variables: health, income, and temperature. These three variables are a minimal adjustment set, the minimum set (or sets) of variables you need to block all confounding pathways.</p>
<p>We could estimate the causal effect using Regression Adjustment: including the minimal set of covariates in our regression.</p>
<p>Instead we’ll use a technique called Inverse Probability Weighting (IPW) to control for these variables:</p>
<p>We’ll use logistic regression to predict the probability of treatment—the propensity score. Then, we’ll calculate inverse probability weights to apply to the linear regression model we fit above.</p>
<p>The propensity score model includes the exposure—net use—as the dependent variable and the minimal adjustment set as the independent variables.</p>
</div>
</section>
<section id="example-model-our-assumptions-1" class="slide level2">
<h2>Example: Model our assumptions</h2>
<div style="font-size: 65%">
<p>The propensity score model is a logistic regression model with the formula <code>net ~ income + health + temperature</code>, which predicts the probability of bed net usage based on the confounders income, health, and temperature.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a>propensity_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb33-2"><a></a>  net <span class="sc">~</span> income <span class="sc">+</span> health <span class="sc">+</span> temperature,</span>
<span id="cb33-3"><a></a>  <span class="at">data =</span> causalworkshop<span class="sc">::</span>net_data,</span>
<span id="cb33-4"><a></a>  <span class="at">family =</span> <span class="fu">binomial</span>()</span>
<span id="cb33-5"><a></a>)</span>
<span id="cb33-6"><a></a></span>
<span id="cb33-7"><a></a><span class="co"># the first six propensity scores</span></span>
<span id="cb33-8"><a></a><span class="fu">head</span>(<span class="fu">predict</span>(propensity_model, <span class="at">type =</span> <span class="st">"response"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     1      2      3      4      5      6 
0.2464 0.2178 0.3230 0.2307 0.2789 0.3060 </code></pre>
</div>
</div>
<p>We can use propensity scores to control for confounding in various ways. In this example, we’ll focus on weighting.</p>
<p>In particular, we’ll compute the inverse probability weight for the <em>average treatment effect</em> (ATE). The ATE represents a particular causal question: what if <em>everyone</em> in the study used bed nets vs.&nbsp;what if <em>no one</em> in the study used bed nets?</p>
<p>To calculate the ATE, we’ll use the <code>broom</code> and <code>propensity</code> packages. broom’s <code>augment()</code> function extracts prediction-related information from the model and joins it to the data. propensity’s <code>wt_ate()</code> function calculates the inverse probability weight given the propensity score and exposure.</p>
</div>
</section>
<section id="example-model-our-assumptions-2" class="slide level2">
<h2>Example: Model our assumptions</h2>
<div style="font-size: 65%">
<p>For inverse probability weighting, the ATE weight is the probability of receiving the treatment you actually received. In other words, if you used a bed net, the ATE weight is the probability that you used a net, and if you did <em>not</em> use a net, it is the probability that you did <em>not</em> use a net.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a></a>net_data_wts <span class="ot">&lt;-</span> propensity_model <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a></a>  broom<span class="sc">::</span><span class="fu">augment</span>(<span class="at">newdata =</span> causalworkshop<span class="sc">::</span>net_data, <span class="at">type.predict =</span> <span class="st">"response"</span>) <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a></a>  <span class="co"># .fitted is the value predicted by the model</span></span>
<span id="cb35-4"><a></a>  <span class="co"># for a given observation</span></span>
<span id="cb35-5"><a></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">wts =</span> propensity<span class="sc">::</span><span class="fu">wt_ate</span>(.fitted, net))</span>
<span id="cb35-6"><a></a></span>
<span id="cb35-7"><a></a>net_data_wts <span class="sc">|&gt;</span></span>
<span id="cb35-8"><a></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(net, .fitted, wts) <span class="sc">|&gt;</span></span>
<span id="cb35-9"><a></a>  dplyr<span class="sc">::</span><span class="fu">slice_head</span>(<span class="at">n=</span><span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 3
   net   .fitted   wts
   &lt;lgl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 FALSE   0.246  1.33
 2 FALSE   0.218  1.28
 3 FALSE   0.323  1.48
 4 FALSE   0.231  1.30
 5 FALSE   0.279  1.39
 6 FALSE   0.306  1.44
 7 FALSE   0.332  1.50
 8 FALSE   0.168  1.20
 9 FALSE   0.222  1.29
10 FALSE   0.255  1.34
11 FALSE   0.215  1.27
12 FALSE   0.220  1.28
13 FALSE   0.195  1.24
14 FALSE   0.167  1.20
15 FALSE   0.200  1.25
16 TRUE    0.413  2.42</code></pre>
</div>
</div>
</div>
</section>
<section id="example-model-our-assumptions-3" class="slide level2">
<h2>Example: Model our assumptions</h2>
<div style="font-size: 65%">
<p><code>wts</code> represents the amount each observation will be up-weighted or down-weighted in the outcome model we will fit.</p>
<p>For instance, the 16th household used a bed net and had a predicted probability of 0.41. That’s a pretty low probability considering they did, in fact, use a net, so their weight is higher at 2.42. In other words, this household will be up-weighted compared to the naive linear model we fit above.</p>
<p>The first household did <em>not</em> use a bed net; they’re predicted probability of net use was 0.25 (or put differently, a predicted probability of <em>not</em> using a net of 0.75). That’s more in line with their observed value of <code>net</code>, but there’s still some predicted probability of using a net, so their weight is 1.28.</p>
</div>
</section>
<section id="example-diagnose-our-models" class="slide level2">
<h2>Example: Diagnose our models</h2>
<div class="columns">
<div class="column" style="font-size: 65%">
<p>The goal of propensity score weighting is to weight the population of observations such that the distribution of confounders is balanced between the exposure groups.</p>
<p>In principle, we’re removing the arrows between the confounders and exposure in the DAG, so that the confounding paths no longer distort our estimates.</p>
</div><div class="column" style="font-size: 65%">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a></a><span class="fu">library</span>(halfmoon)</span>
<span id="cb37-2"><a></a><span class="fu">ggplot</span>(net_data_wts, <span class="fu">aes</span>(.fitted)) <span class="sc">+</span></span>
<span id="cb37-3"><a></a>  halfmoon<span class="sc">::</span><span class="fu">geom_mirror_histogram</span>(</span>
<span id="cb37-4"><a></a>    <span class="fu">aes</span>(<span class="at">fill =</span> net),</span>
<span id="cb37-5"><a></a>    <span class="at">bins =</span> <span class="dv">50</span></span>
<span id="cb37-6"><a></a>  ) <span class="sc">+</span></span>
<span id="cb37-7"><a></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> abs) <span class="sc">+</span></span>
<span id="cb37-8"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"propensity score"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-mirror-histogram-net-data-unweighted" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-mirror-histogram-net-data-unweighted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-mirror-histogram-net-data-unweighted-1.png" width="960">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mirror-histogram-net-data-unweighted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24: A mirrored histogram of the propensity scores of those who used nets (top, blue) versus those who who did not use nets (bottom, orange). The range of propensity scores is similar between groups, with those who used nets slightly to the left of those who didn’t, but the shapes of the distribution are different.
</figcaption>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="example-diagnose-our-models-1" class="slide level2">
<h2>Example: Diagnose our models</h2>
<div class="columns">
<div class="column" style="font-size: 65%">
<p>The weighted propensity score creates a pseudo-population where the distributions are much more similar:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a></a><span class="fu">ggplot</span>(net_data_wts, <span class="fu">aes</span>(.fitted)) <span class="sc">+</span></span>
<span id="cb38-2"><a></a>  halfmoon<span class="sc">::</span><span class="fu">geom_mirror_histogram</span>(</span>
<span id="cb38-3"><a></a>    <span class="fu">aes</span>(<span class="at">group =</span> net),</span>
<span id="cb38-4"><a></a>    <span class="at">bins =</span> <span class="dv">50</span></span>
<span id="cb38-5"><a></a>  ) <span class="sc">+</span></span>
<span id="cb38-6"><a></a>  halfmoon<span class="sc">::</span><span class="fu">geom_mirror_histogram</span>(</span>
<span id="cb38-7"><a></a>    <span class="fu">aes</span>(<span class="at">fill =</span> net, <span class="at">weight =</span> wts),</span>
<span id="cb38-8"><a></a>    <span class="at">bins =</span> <span class="dv">50</span>,</span>
<span id="cb38-9"><a></a>    <span class="at">alpha =</span> .<span class="dv">5</span></span>
<span id="cb38-10"><a></a>  ) <span class="sc">+</span></span>
<span id="cb38-11"><a></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> abs) <span class="sc">+</span></span>
<span id="cb38-12"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"propensity score"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div><div class="column" style="font-size: 65%">
<div class="cell">
<div class="cell-output-display">
<div id="fig-mirror-histogram-net-data-weighted" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-mirror-histogram-net-data-weighted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-mirror-histogram-net-data-weighted-1.png" width="960">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mirror-histogram-net-data-weighted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25: A mirrored histogram of the propensity scores of those who used nets (top, blue) versus those who did not use nets (bottom, orange). The dark regions represent the unweighted distributions, and the lighter regions represent the weighted distributions. The ATE weights up-weight the groups to be similar in range and shape of the distribution of propensity scores.
</figcaption>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="example-diagnose-our-models-2" class="slide level2">
<h2>Example: Diagnose our models</h2>
<div class="columns">
<div class="column" style="font-size: 65%">
<p>We might also want to know how well-balanced the groups are by each confounder. One way to do this is to calculate the standardized mean differences (SMDs) for each confounder with and without weights. We’ll calculate the SMDs with <code>tidy_smd()</code> then plot them with <code>geom_love()</code> (see <a href="supplemental/smd.html">SMD</a>).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a></a>plot_df <span class="ot">&lt;-</span> tidysmd<span class="sc">::</span><span class="fu">tidy_smd</span>(</span>
<span id="cb39-2"><a></a>  net_data_wts,</span>
<span id="cb39-3"><a></a>  <span class="fu">c</span>(income, health, temperature),</span>
<span id="cb39-4"><a></a>  <span class="at">.group =</span> net,</span>
<span id="cb39-5"><a></a>  <span class="at">.wts =</span> wts</span>
<span id="cb39-6"><a></a>)</span>
<span id="cb39-7"><a></a></span>
<span id="cb39-8"><a></a>plot_df <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(</span>
<span id="cb39-9"><a></a>  <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">abs</span>(smd), <span class="at">y =</span> variable,</span>
<span id="cb39-10"><a></a>    <span class="at">group =</span> method, <span class="at">color =</span> method</span>
<span id="cb39-11"><a></a>  )</span>
<span id="cb39-12"><a></a>) <span class="sc">+</span> tidysmd<span class="sc">::</span><span class="fu">geom_love</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div><div class="column" style="font-size: 65%">
<div class="cell">
<div class="cell-output-display">
<div id="fig-love-plot-net-data" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-love-plot-net-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-love-plot-net-data-1.png" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-love-plot-net-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;26: A love plot representing the standardized mean differences (SMD) between exposure groups of three confounders: temperature, income, and health. Before weighting, there are considerable differences in the groups. After weighting, the confounders are much more balanced between groups.
</figcaption>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="example-diagnose-our-models-3" class="slide level2">
<h2>Example: Diagnose our models</h2>
<div class="columns">
<div class="column" style="font-size: 65%">
<p>Before we apply the weights to the outcome model, let’s check their overall distribution for extreme weights.</p>
<p>Extreme weights can destabilize the estimate and variance in the outcome model, so we want to be aware of it.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a></a>net_data_wts <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(wts)) <span class="sc">+</span></span>
<span id="cb40-3"><a></a>  <span class="fu">geom_density</span>(</span>
<span id="cb40-4"><a></a>    <span class="at">fill =</span> <span class="st">"#CC79A7"</span></span>
<span id="cb40-5"><a></a>    , <span class="at">color =</span> <span class="cn">NA</span></span>
<span id="cb40-6"><a></a>    , <span class="at">alpha =</span> <span class="fl">0.8</span></span>
<span id="cb40-7"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div><div class="column" style="font-size: 65%">
<div class="cell">
<div class="cell-output-display">
<div id="fig-ate-density-net-data" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-ate-density-net-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-ate-density-net-data-1.png" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ate-density-net-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27: A density plot of the average treatment effect (ATE) weights. The plot is skewed, with higher values towards 8. This may indicate a problem with the model, but the weights aren’t so extreme to destabilize the variance of the estimate.
</figcaption>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="example-estimate-the-causal-effect" class="slide level2">
<h2>Example: Estimate the causal effect</h2>
<div style="font-size: 65%">
<p>We’re now ready to use the ATE weights to (attempt to) account for confounding in the naive linear regression model. Fitting such a model is pleasantly simple in this case: we fit the same model as before but with <code>weights = wts</code>, which will incorporate the inverse probability weights.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a></a>net_data_wts <span class="sc">|&gt;</span></span>
<span id="cb41-2"><a></a>  <span class="fu">lm</span>(malaria_risk <span class="sc">~</span> net, <span class="at">data =</span> _, <span class="at">weights =</span> wts) <span class="sc">|&gt;</span></span>
<span id="cb41-3"><a></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(<span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term   estimate std.error statistic  p.value conf.low
  &lt;chr&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 (Inte…     42.7     0.442      96.7 0            41.9
2 netTR…    -12.5     0.624     -20.1 5.50e-81    -13.8
# ℹ 1 more variable: conf.high &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a></a>estimates <span class="ot">&lt;-</span> net_data_wts <span class="sc">|&gt;</span></span>
<span id="cb43-2"><a></a>  <span class="fu">lm</span>(malaria_risk <span class="sc">~</span> net, <span class="at">data =</span> _, <span class="at">weights =</span> wts) <span class="sc">|&gt;</span></span>
<span id="cb43-3"><a></a>  broom<span class="sc">::</span><span class="fu">tidy</span>(<span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb43-4"><a></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"netTRUE"</span>) <span class="sc">|&gt;</span></span>
<span id="cb43-5"><a></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(estimate, <span class="fu">starts_with</span>(<span class="st">"conf"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb43-6"><a></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>( </span>
<span id="cb43-7"><a></a>    dplyr<span class="sc">::</span><span class="fu">across</span>( <span class="fu">everything</span>(), \(x)<span class="fu">round</span>(x, <span class="at">digits =</span> <span class="dv">1</span>) ) </span>
<span id="cb43-8"><a></a>  )</span>
<span id="cb43-9"><a></a>estimates</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  estimate conf.low conf.high
     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1    -12.5    -13.8     -11.3</code></pre>
</div>
</div>
<p>The estimate for the average treatment effect is -12.5 (95% CI -13.8, -11.3).</p>
</div>
</section>
<section id="example-estimate-the-causal-effect-1" class="slide level2">
<h2>Example: Estimate the causal effect</h2>
<div style="font-size: 65%">
<p>Unfortunately, the confidence intervals don’t account for the dependence within the weights! Generally, confidence intervals for propensity-score weighted models will be too narrow unless we correct for this dependence.</p>
<p>The nominal coverage of the confidence intervals will thus be wrong (they aren’t 95% CIs because their coverage is much lower than 95%) and may lead to misinterpretation.</p>
<p>For this example, we’ll use the bootstrap, a flexible tool that calculates distributions of parameters using re-sampling. We’ll use the <code>rsample</code> package from <code>tidymodels</code> to work with bootstrap samples.</p>
</div>
</section>
<section id="example-estimate-the-causal-effect-2" class="slide level2">
<h2>Example: Estimate the causal effect</h2>
<div style="font-size: 65%">
<p>Because the the inverse probability weights are not fixed values (they depend on the data), we need to account for this by bootstrapping the <em>entire modeling process</em>.</p>
<p>For every bootstrap sample, we need to fit the propensity score model, calculate the inverse probability weights, then fit the weighted outcome model, using the following function:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a></a>fit_ipw <span class="ot">&lt;-</span> <span class="cf">function</span>(split, ...) {</span>
<span id="cb45-2"><a></a>  <span class="co"># get bootstrapped data sample with `rsample::analysis()`</span></span>
<span id="cb45-3"><a></a>  .df <span class="ot">&lt;-</span> rsample<span class="sc">::</span><span class="fu">analysis</span>(split)</span>
<span id="cb45-4"><a></a></span>
<span id="cb45-5"><a></a>  <span class="co"># fit propensity score model</span></span>
<span id="cb45-6"><a></a>  propensity_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb45-7"><a></a>    net <span class="sc">~</span> income <span class="sc">+</span> health <span class="sc">+</span> temperature,</span>
<span id="cb45-8"><a></a>    <span class="at">data =</span> .df,</span>
<span id="cb45-9"><a></a>    <span class="at">family =</span> <span class="fu">binomial</span>()</span>
<span id="cb45-10"><a></a>  )</span>
<span id="cb45-11"><a></a></span>
<span id="cb45-12"><a></a>  <span class="co"># calculate inverse probability weights</span></span>
<span id="cb45-13"><a></a>  .df <span class="ot">&lt;-</span> propensity_model <span class="sc">|&gt;</span></span>
<span id="cb45-14"><a></a>    broom<span class="sc">::</span><span class="fu">augment</span>(<span class="at">type.predict =</span> <span class="st">"response"</span>, <span class="at">data =</span> .df) <span class="sc">|&gt;</span></span>
<span id="cb45-15"><a></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">wts =</span> propensity<span class="sc">::</span><span class="fu">wt_ate</span>(.fitted, net))</span>
<span id="cb45-16"><a></a></span>
<span id="cb45-17"><a></a>  <span class="co"># fit correctly bootstrapped ipw model</span></span>
<span id="cb45-18"><a></a>  <span class="fu">lm</span>(malaria_risk <span class="sc">~</span> net, <span class="at">data =</span> .df, <span class="at">weights =</span> wts) <span class="sc">|&gt;</span></span>
<span id="cb45-19"><a></a>    broom<span class="sc">::</span><span class="fu">tidy</span>()</span>
<span id="cb45-20"><a></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div>
</section>
<section id="example-estimate-the-causal-effect-3" class="slide level2">
<h2>Example: Estimate the causal effect</h2>
<div style="font-size: 65%">
<p>We generate a distribution of estimates as follows:</p>
<div class="cell">
<details class="code-fold">
<summary>bootstrap - ipw - estimate</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a></a><span class="co"># create bootstrap samples</span></span>
<span id="cb46-2"><a></a>bootstrapped_net_data <span class="ot">&lt;-</span> rsample<span class="sc">::</span><span class="fu">bootstraps</span>(</span>
<span id="cb46-3"><a></a>  causalworkshop<span class="sc">::</span>net_data,</span>
<span id="cb46-4"><a></a>  <span class="at">times =</span> <span class="dv">1000</span>,</span>
<span id="cb46-5"><a></a>  <span class="co"># required to calculate CIs later</span></span>
<span id="cb46-6"><a></a>  <span class="at">apparent =</span> <span class="cn">TRUE</span></span>
<span id="cb46-7"><a></a>)</span>
<span id="cb46-8"><a></a></span>
<span id="cb46-9"><a></a><span class="co"># create ipw and fit each bootstrap sample</span></span>
<span id="cb46-10"><a></a>ipw_results <span class="ot">&lt;-</span> bootstrapped_net_data <span class="sc">|&gt;</span></span>
<span id="cb46-11"><a></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb46-12"><a></a>    <span class="at">boot_fits =</span> purrr<span class="sc">::</span><span class="fu">map</span>(splits, fit_ipw))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>distribution</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a></a>ipw_results <span class="sc">|&gt;</span></span>
<span id="cb47-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb47-3"><a></a>    <span class="at">estimate =</span> <span class="fu">map_dbl</span>(</span>
<span id="cb47-4"><a></a>      boot_fits,</span>
<span id="cb47-5"><a></a>      <span class="co"># pull the `estimate` for `netTRUE` for each fit</span></span>
<span id="cb47-6"><a></a>      \(.fit) .fit <span class="sc">|&gt;</span></span>
<span id="cb47-7"><a></a>        <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"netTRUE"</span>) <span class="sc">|&gt;</span></span>
<span id="cb47-8"><a></a>        <span class="fu">pull</span>(estimate)</span>
<span id="cb47-9"><a></a>    )</span>
<span id="cb47-10"><a></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb47-11"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(estimate)) <span class="sc">+</span></span>
<span id="cb47-12"><a></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">"#D55E00FF"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-bootstrap-estimates-net-data" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-bootstrap-estimates-net-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-bootstrap-estimates-net-data-1.png" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bootstrap-estimates-net-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;28: “A histogram of 1,000 bootstrapped estimates of the effect of net use on malaria risk. The spread of these estimates accounts for the dependency and uncertainty in the use of IPW weights.”
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="example-estimate-the-causal-effect-4" class="slide level2">
<h2>Example: Estimate the causal effect</h2>
<div style="font-size: 65%">
<p><a href="#/fig-bootstrap-estimates-net-data" class="quarto-xref">Figure&nbsp;28</a> gives a sense of the variation in <code>estimate</code>, but let’s calculate 95% confidence intervals from the bootstrapped distribution using rsample’s <code>int_t()</code> :</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a></a>boot_estimate <span class="ot">&lt;-</span> ipw_results <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a></a>  <span class="co"># calculate T-statistic-based CIs</span></span>
<span id="cb48-3"><a></a>  rsample<span class="sc">::</span><span class="fu">int_t</span>(boot_fits) <span class="sc">|&gt;</span></span>
<span id="cb48-4"><a></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"netTRUE"</span>)</span>
<span id="cb48-5"><a></a></span>
<span id="cb48-6"><a></a>boot_estimate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  term    .lower .estimate .upper .alpha .method  
  &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;    
1 netTRUE  -13.4     -12.5  -11.6   0.05 student-t</code></pre>
</div>
</div>
<p>Now we have a confounder-adjusted estimate with correct standard errors. The estimate of the effect of <em>all</em> households using bed nets versus <em>no</em> households using bed nets on malaria risk is -12.5 (95% CI -13.4, -11.6).</p>
<p>Bed nets do indeed seem to reduce malaria risk in this study.</p>
</div>
</section>
<section id="example-conduct-sensitivity-analysis" class="slide level2">
<h2>Example: Conduct sensitivity analysis</h2>
<div style="font-size: 65%">
<p>When conducting a causal analysis, it’s a good idea to use sensitivity analyses to test your assumptions. There are many potential sources of bias in any study and many sensitivity analyses to go along with them; we’ll focus on the assumption of no confounding.</p>
<p>When we have less information about unmeasured confounders, we can use tipping point analysis to ask how much confounding it would take to tip my estimate to the null. In other words, what would the strength of the unmeasured confounder have to be to explain our results away? The <code>tipr</code> package is a toolkit for conducting sensitivity analyses.</p>
</div>
</section>
<section id="example-conduct-sensitivity-analysis-1" class="slide level2">
<h2>Example: Conduct sensitivity analysis</h2>
<div style="font-size: 65%">
<p>Assume an unknown, normally-distributed confounder.</p>
<p>The <code>tip_coef()</code> function takes an estimate (e.g.&nbsp;the upper or lower bound of the coefficient) and further requires either the</p>
<ul>
<li>the scaled differences in means of the confounder between exposure groups, or</li>
<li>the effect of the confounder on the outcome.</li>
</ul>
<p>For the estimate, we’ll use <code>conf.high</code>, which is closer to 0 (the null), and ask: how much would the confounder have to affect malaria risk to have an unbiased upper confidence interval of 0?</p>
<p>We’ll use tipr to calculate this answer for 5 scenarios, where the mean difference in the confounder between exposure groups is 1, 2, 3, 4, or 5.</p>
</div>
</section>
<section id="example-sensitivity-analysis" class="slide level2">
<h2>Example: Sensitivity analysis</h2>
<div style="font-size: 65%">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a></a>tipping_points <span class="ot">&lt;-</span> tipr<span class="sc">::</span><span class="fu">tip_coef</span>(boot_estimate<span class="sc">$</span>.upper, <span class="at">exposure_confounder_effect =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>)</span>
<span id="cb50-2"><a></a></span>
<span id="cb50-3"><a></a>tipping_points <span class="sc">|&gt;</span></span>
<span id="cb50-4"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(confounder_outcome_effect, exposure_confounder_effect)) <span class="sc">+</span></span>
<span id="cb50-5"><a></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"#009E73"</span>, <span class="at">linewidth =</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb50-6"><a></a>  <span class="fu">geom_point</span>(<span class="at">fill =</span> <span class="st">"#009E73"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">shape =</span> <span class="dv">21</span>) <span class="sc">+</span></span>
<span id="cb50-7"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb50-8"><a></a>    <span class="at">x =</span> <span class="st">"Confounder-Outcome Effect"</span>,</span>
<span id="cb50-9"><a></a>    <span class="at">y =</span> <span class="st">"Scaled mean differences in</span><span class="sc">\n</span><span class="st"> confounder between exposure groups"</span></span>
<span id="cb50-10"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-tip-coef-net" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-tip-coef-net-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="BSMM_8740_lec_07_files/figure-revealjs/fig-tip-coef-net-1.png" width="624">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tip-coef-net-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;29: A tipping point analysis under several confounding scenarios where the unmeasured confounder is a normally-distributed continuous variable. The line represents the strength of confounding necessary to tip the upper confidence interval of the causal effect estimate to 0. The x-axis represents the coefficient of the confounder-outcome relationship adjusted for the exposure and the set of measured confounders. The y-axis represents the scaled mean difference of the confounder between exposure groups.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="more" class="slide level2">
<h2>More</h2>
<ul>
<li>Read <a href="https://chabefer.github.io/STCI/index.html">Statistical tools for causal inference</a></li>
<li>Read <a href="https://www.r-causal.org/">Causal inference in R</a></li>
</ul>
</section>
<section id="summary-assumptions" class="slide level2">
<h2>Summary: Assumptions</h2>
<div style="font-size: large">
<p>In order to estimate a causal effect when there is a confounder, we need the following assumptions</p>
<ol type="1">
<li><p><span class="math inline">\((Y^1,Y^0)\, \bot\, D\mid X\)</span> (conditional independence)</p></li>
<li><p><span class="math inline">\(0&lt;\mathbb{P}(D=1 \mid X) &lt;1\)</span> (common support)</p></li>
</ol>
<p>These two assumptions yield the following identity</p>
<p><span class="math display">\[
\begin{align}   E\big[Y^1-Y^0\mid X\big] &amp; = E\big[Y^1 - Y^0 \mid X,D=1\big]                        \\            &amp; = E\big[Y^1\mid X,D=1\big] - E\big[Y^0\mid X,D=0\big]   \\            &amp; = E\big[Y\mid X,D=1\big] - E\big[Y\mid X,D=0\big]     \end{align}
\]</span></p>
<p>where each value of <span class="math inline">\(Y\)</span> is determined by the switching equation.</p>
<p>Whereas we need treatment to be conditionally independent of both potential outcomes to identify the ATE, we need only treatment to be conditionally independent of <span class="math inline">\(Y^0\)</span> to identify the ATT and the fact that there exist some units in the control group for each treatment strata. Note, the reason for the common support assumption is because we are weighting the data; without common support, we cannot calculate the relevant weights.</p>
</div>
</section>
<section id="recap" class="slide level2">
<h2>Recap</h2>
<ul>
<li>We introduced the fundamental problems of inference and the biases of some intuitive estimators,</li>
<li>We developed a basic understanding of the tools used to state and then satisfy causality assumptions,</li>
<li>We looked at an example of how econometric methods recover treatment effects.</li>
</ul>


</section></section>

    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://bsmm-8740-fall-2025.github.io/osb/">bsmm-8740-fall-2025.github.io/osb</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/multiplex/socket.io.js"></script>
  <script src="../site_libs/revealjs/plugin/multiplex/multiplex.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"numbers":true},
'chalkboard': {"buttons":true},
'multiplex': {"secret":null,"id":"f642a81e0524a551","url":"https://reveal-multiplex.glitch.me/"},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 5.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/bsmm-8740-fall-2025\.github\.io\/osb\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>