---
title: "DiD"
---

## The simplest case

In the canonical DiD model, we have:

-   periods: treatment occurs (for some units) in period 2
-   Identification of the ATT from parallel trends and no anticipation
-   Estimation using sample analogs, equivalent to OLS with TWFE
-   A large number of independent observations (or clusters)

## Canonical DiD -- with math

-   Panel data on $Y_{it}$ for $t=1,2$ and $i = 1,...,N$
-   **Treatment timing:** Some units ($D_i=1$) are treated in period $2$; everyone else is untreated $(D_i=0)$
-   **Potential outcomes (POs):** Observe $Y_{it}(1) \equiv Y_{it}(0,1)$ for treated units; and $Y_{it}(0) \equiv Y_{it}(0,0)$ for comparison

## Key Identifying Assumption - Parallel Trends

-   The **parallel trends** assumption states that if the treatment hadn't occurred, average outcomes for the treatment and control groups would have evolved in parallel $$\underbrace{ E[Y_{i2}(0) - Y_{i1}(0) \mid D_i =1] }_{\text{Counterfactual change for treated group}}= \underbrace{ E[Y_{i2}(0) - Y_{i1}(0) \mid D_i =0] }_{\text{Change for untreated group}} $$
-   The parallel trends assumption can also be viewed as a **selection bias stability** assumption:\
    $$\underbrace{ E[Y_{i2}(0)  \mid D_i =1] - E[Y_{i2}(0) \mid D_i=0] }_{\text{Selection bias in period 2}}= \underbrace{ E[Y_{i1}(0)  \mid D_i =1] - E[Y_{i1}(0) \mid D_i=0] }_{\text{Selection bias in period 1}} $$
-   PT allows for there to be selection bias! But it must be stable over time

## Key identifying assumptions

-   **Parallel trends**

$$
    \begin{align}
    \mathbb{E}[Y_{i2}(0) - Y_{i1}(0) \vert D_i = 1]  = \mathbb{E}[Y_{i2}(0) - Y_{i1}(0) \vert D_i = 0]
    \end{align}
$$ {#eq-pt-2periods}

-   **No anticipation:** $Y_{i1}(1) = Y_{i1}(0)$
    -   Intuitively, outcome in period 1 isn't affected by treatment status in period 2
    -   Often left implicit in notation, but important for interpreting DiD estimand as a causal effect in period 2

## Identification

-   **Target parameter:** Average treatment effect on the treated (ATT) in period 2 $$\tau_{ATT} = E[Y_{i2}(1) - Y_{i2}(0) | D_i=1] $$
-   Under parallel trends and no anticipation, can show that

$$
\tau_{ATT} = \underbrace{(E[Y_{i2} | D_i = 1] - E[Y_{i1}| D_i =1])}_{\text{Change for treated}} - \underbrace{(E[Y_{i2} | D_i = 0] - E[Y_{i1}| D_i =0]) }_{\text{Change for control}}
$$ a "difference-in-differences"" of population means

## Proof of Identification Argument

-   Start with $$E[Y_{i2}- Y_{i1}| D_i =1] - E[Y_{i2} - Y_{i1}| D_i =0]$$
-   Apply definition of POs to obtain: $$E[Y_{i2}(1) - Y_{i1}(1)| D_i =1] - E[Y_{i2}(0) - Y_{i1}(0)| D_i =0]$$
-   Use No Anticipation to substitute $Y_{i1}(0)$ for $Y_{i1}(1)$: $$E[Y_{i2}(1) - Y_{i1}(0)| D_i =1] - E[Y_{i2}(0) - Y_{i1}(0)| D_i =0]$$
-   Add and subtract \$E\[ Y\_{i2}(0) \| D_i =1\] \$ to obtain: $$
        \begin{align*}
            & E[ Y_{i2}(1) - Y_{i2}(0) | D_i =1] + \\
            & \hspace{1cm} \left[ (E[Y_{i2}(0) | D_i = 1] - E[Y_{i1}(0)| D_i =1]) - (E[Y_{i2}(0) | D_i = 0] - E[Y_{i1}(0)| D_i =0]) \right]
        \end{align*}
        $$
-   Cancel the last terms using PT to get $E[Y_{i2}(1) - Y_{i2}(0) | D_i = 1] = \tau_{ATT}$

## Estimation and Inference

-   The most conceptually simple estimator replaces population means with sample analogs: $$\hat{\tau}_{DiD} = (\bar{Y}_{12} - \bar{Y}_{11}) - (\bar{Y}_{02} - \bar{Y}_{01}) $$ where $\bar{Y}_{dt}$ is sample mean for group $d$ in period $t$
-   Conveniently, $\hat\tau_{DID}$ is algebraically equal to OLS coefficient $\hat\beta$ from $$\begin{align*}
    Y_{it} = \alpha_i + \phi_t + D_{it} \beta  + \epsilon_{it}, 
    \end{align*}$$ {#eq-TWFE-2-periods} where $D_{it} = D_i * 1[t=2]$. Also equivalent to $\beta$ from $\Delta Y_{i} = \alpha +  \Delta D_i \beta + u_{it}$.
-   **Inference:** And clustered standard errors are valid as number of clusters grows large

## Characterizing the recent literature

We can group the recent innovations in DiD lit by which elements of the canonical model they relax:

-   **Multiple periods and staggered treatment timing**
-   **Relaxing or allowing PT to be violated**
-   **Inference with a small number of clusters**

------------------------------------------------------------------------

## Staggered Timing

-   Remember that in the canonical DiD model we had:

    -   Two periods and a common treatment date
    -   Identification from parallel trends and no anticipation
    -   A large number of clusters for inference

-   A very active recent literature has focused on relaxing the first assumption: **what if there are multiple periods and units adopt treatment at different times?**

-   This literature typically maintains the remaining ingredients: parallel trends and many clusters

## Overview of Staggered Timing Literature

-   Negative results: TWFE OLS doesn't give us what we want with treatment effect heterogeneity
-   New estimators: perform better under treatment effect heterogeneity

## Staggered timing set-up

-   Panel of observations for periods $t = 1,...,T$
-   Suppose units adopt a binary treatment at different dates $G_i \in \{1,...,T \} \cup \infty$ (where $G_i = \infty$ means "never-treated")
    -   Active literature considering cases with continuous treatment & treatments that turn on/off (see Section 3.4 of review paper)
-   Potential outcomes $Y_{it}(g)$ -- depend on time and time you were first-treated

## Extending the Identifying Assumptions

-   The key identifying assumptions from the canonical model are extended in the natural way

-   **Parallel trends:** Intuitively, says that if treatment hadn't happened, all "adoption cohorts'' would have parallel average outcomes in all periods $$ E[ Y_{it}(\infty) - Y_{i,t-1}(\infty) | G_i = g ] = E[ Y_{it}(\infty) - Y_{i,t-1}(\infty) | G_i = g' ] \text{ for all } g,g',t$$ Note: can impose slightly weaker versions (e.g. only require PT post-treatment)

-   **No anticipation:** Intuitively, says that treatment has no impact before it is implemented $$Y_{it}(g) = Y_{it}(\infty) \text{ for all } t<g$$

## Negative results

-   Suppose we again run the regression $$Y_{it} = \alpha_i + \phi_t + D_{it} \beta  + \epsilon_{it}, $$ where $D_{it} = 1[t \geq G_i]$ is a treatment indicator.
-   Suppose we're willing to assume no anticipation and parallel trends across all adoption cohorts as described above
-   Good news: If each unit has a constant treatment effect over time, $Y_{it}(g) - Y_{it}(\infty) \equiv \tau_i$, get a weighted avg of $\tau_i$
-   Bad news: if treatment effects are heterogeneous (within unit over time), then $\beta$ may put negative weights on treatment effects for some units and time periods
    -   E.g., if treatment effect depends on time since treatment, ${Y_{it}(t-r) - Y_{it}(\infty) = \tau_{r}}$, then some $\tau_r$ values may get negative weight

## Where do these negative results come from?

-   The intuition for these negative results is that the TWFE OLS specification combines two sources of comparisons:
    -   **Clean comparisons:** DiD's between treated and not-yet-treated units
    -   **Forbidden comparisons:** DiD's between newly-treated and already-treated units
-   These forbidden comparisons can lead to negative weights: the control group is already treated, so we run into problems if their treatment effects change over time

## Some intuition for forbidden comparisons

-   Consider the two period model, except suppose now that our two groups are **always-treated\* units (treated in both periods) and** switchers\*\* (treated only in period 2)
-   With two periods, the coefficient $\beta$ from \$ Y\_{it} = \alpha\*i +\* \phi\*t + D\*{it} \beta  + \epsilon{it}\$ is the same as from the first-differenced regression $\Delta Y_i = \alpha + \Delta D_i \beta + u_i$
-   Observe that $\Delta D_i$ is one for switchers and zero for stayers. \\ That is, the stayers function as the \`\`control group''! Thus, $$\hat\beta =  \underbrace{ \left(\bar{Y}_{Switchers, 2} - \bar{Y}_{Switchers, 1} \right) }_{\text{Change for switchers}} - \underbrace{ \left(\bar{Y}_{AT, 2} - \bar{Y}_{AT, 1} \right) }_{\text{Change for always treated}}  $$
-   Problem: if the effect for the always-treated grows over time, that will enter $\hat\beta$ negatively!
-   With staggered timing, units who are treated early are like \`\`always-treated'' in later pairs of periods

## Second Intuition for Negative Weights

The literature has placed a lot of emphasis on the fact that some treatment effects may get negative weights

-   But even if the weights are non-negative, they might not give us the most intuitive parameter
-   For example, suppose each unit $i$ has treatment effect $\tau_i$ in every period if they are treated (no dynamics). Then $\beta$ gives a weighted average of the $\tau_i$ where the weights are largest for units treated closest to the middle of the panel
-   It is not obvious that these weights are relevant for policy, even if they are all non-negative!

## Issues with dynamic TWFE

-   {sun_estimating_2020} show that similar issues arise with dynamic TWFE specifications: $$
        \begin{equation*}
            Y_{i,t} = \alpha_i + \lambda_t +  \sum_{k \neq 0} \gamma_k D_{i,t}^{k} + \varepsilon_{i,t},
        \end{equation*}$$ where $D_{i,t}^{k} = 1\left\{t-G_{i}=k\right\}$ are \`\`event-time'' dummies.
-   Like for the static spec, $\gamma_k$ may be a non-convex weighted average of the dynamic treatment effect $k$ periods after treatment
-   SA also show that $\gamma_k$ may be \`\`contaminated'' by treatment effects at lags $k'\neq k$

## Dynamic TWFE - Continued

-   The results in SA suggest that interpreting the $\hat\gamma_k$ for $k=1,2,...$ as estimates of the dynamic effects of treatment may be misleading

-   These results also imply that pre-trends tests of the $\gamma_k$ for $k<0$ may be misleading -- could be non-zero even if parallel trends holds, since they may be \`\`contaminated'' by post-treatment effects!

-   The issues discussed in SA arise if dynamic path of treatment effects is heterogeneous across adoption cohorts

    -   Biases may be less severe than for \`\`static'' specs if dynamic patterns are similar across cohorts
